/* eslint-disable */
/**
 * Project Impact Analyzer
 * =======================
 * Answers "which projects and features does this change affect, and what should each owner know?"
 * by joining three artifacts that already exist:
 *
 *   1. the diff report from ./pr-behavior-diff.ts  - which route signatures moved, and the full
 *                                                    list of changed backend files
 *   2. .behavior-manifest.json                     - every route, its service calls, its imports
 *   3. graphify-out/graph.json                     - who reaches whom, and which subsystem a file
 *                                                    belongs to
 *
 * The reason this is a separate script rather than more output from the gate: the gate is
 * deliberately text-local. A route's hash is computed from its own file, which is what lets any
 * git revision be signed without a checkout - and which means a change inside a service moves no
 * hash at all. That is not a bug in the gate, it is the price of its portability. This script
 * pays the other side: it starts from the changed FILES and works forward to the routes they
 * reach, so a pull request touching only secret-service.ts still reports the routes behind it.
 *
 * Reach is established two ways, because neither alone is sufficient:
 *   - the DI bridge (./di-bridge.ts), for service modules, which the import graph cannot see
 *     through because routers reach services via `server.services.<key>`
 *   - the graph's reverse closure, for everything else (lib, helpers, plugins, shared fns)
 *
 * Both are capped. A change to src/lib/errors/index.ts reaches 471 route files; printing them is
 * not analysis. Past the threshold a file is reported as wide-impact with a count and the
 * subsystems involved.
 *
 * Ownership is auto-derived from graph communities so this works with no configuration. A
 * committed .behavior-projects.json overlays human metadata (owner, team, Slack) on top; see the
 * `discover-projects` command, which scaffolds one.
 *
 * Usage:
 *     npm run behavior:pr -- --url 7638 --report /tmp/report.json
 *     npm run behavior:analyze -- --report /tmp/report.json --markdown /tmp/impact.md
 *     npm run behavior:discover-projects
 */

import { existsSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { parseArgs } from "node:util";

import { DiBridge, loadDiBridge, ROUTES_INDEX } from "./di-bridge";
import { Community, GraphIndex, loadGraphIndex } from "./graph-index";
import { AUTHORIZATION_CATEGORY, ChangeFocus, focusChange, FocusMethod, readAtRevision } from "./method-index";
import {
  BACKEND_ROOT,
  BehaviorConfig,
  BehavioralSignature,
  ChangeDetail,
  DEFAULT_CONFIG,
  DEFAULT_GRAPH,
  DEFAULT_MANIFEST,
  DiffReport,
  fail,
  isExcludedPath,
  loadConfig,
  Manifest
} from "./signature-builder";

const DEFAULT_REGISTRY = path.join(BACKEND_ROOT, ".behavior-projects.json");
const DEFAULT_OUTPUT = path.join(BACKEND_ROOT, "project-analysis.json");

const DEFAULT_WIDE_THRESHOLD = 40;
const DEFAULT_MAX_DEPTH = 3;

// ---------------------------------------------------------------------------
// Registry
// ---------------------------------------------------------------------------

interface ProjectDef {
  name: string;
  owner?: string;
  team?: string;
  slack?: string;
  jira?: string;
  status?: string;
  launch_date?: string;
  path_globs?: string[];
  service_keys?: string[];
  communities?: string[];
}

interface ProjectRegistry {
  analysis?: { wide_threshold?: number; max_depth?: number };
  projects: Record<string, ProjectDef>;
}

const REGISTRY_NOTES = [
  "Generated by `npm run behavior:discover-projects`, then edited by hand.",
  "",
  "This file is OPTIONAL. Without it, ./project-analyzer.ts groups changes by Graphify community,",
  "which gives correct subsystem grouping but no human metadata. Filling in owner/team/slack is",
  "what turns 'Secret Versioning & Commits is affected' into 'tell this person, in this channel'.",
  "",
  "Matching precedence per changed file, first hit wins:",
  "  1. path_globs    - a path prefix ('src/services/secret/**'), suffix ('*-dal.ts'), or exact path",
  "  2. service_keys  - the server.services.<key> the file's module is wired to",
  "  3. communities   - a Graphify community name; these are LLM-generated and are RENAMED on every",
  "                     graphify run, so prefer path_globs for anything you rely on",
  "",
  "analysis.wide_threshold: past this many reachable routes a changed file is reported as a count",
  "  and a list of subsystems instead of an enumeration. src/lib/errors/index.ts reaches 471 route",
  "  files; listing them is noise, not impact.",
  "analysis.max_depth: how many import hops to follow back from a changed file."
];

const matchesGlob = (candidate: string, pattern: string): boolean => {
  if (pattern.endsWith("/**")) return candidate.startsWith(pattern.slice(0, -2));
  if (pattern.startsWith("*")) return candidate.endsWith(pattern.slice(1));
  if (pattern.endsWith("*")) return candidate.startsWith(pattern.slice(0, -1));
  return candidate === pattern;
};

const loadRegistry = (registryPath: string): ProjectRegistry | null => {
  if (!existsSync(registryPath)) return null;
  const parsed = JSON.parse(readFileSync(registryPath, "utf-8")) as Partial<ProjectRegistry>;

  // The scaffold writes owner/team/slack as "" for a human to fill in. Left empty they are absent,
  // not present-and-blank, or every unfilled field renders as an empty table cell.
  const projects: Record<string, ProjectDef> = {};
  for (const [id, definition] of Object.entries(parsed.projects ?? {})) {
    const cleaned = { ...definition };
    for (const key of ["owner", "team", "slack", "jira", "status", "launch_date"] as const) {
      if (!cleaned[key]) delete cleaned[key];
    }
    projects[id] = cleaned;
  }

  return { analysis: parsed.analysis ?? {}, projects };
};

// ---------------------------------------------------------------------------
// Risk
// ---------------------------------------------------------------------------

type Risk = "critical" | "high" | "medium" | "low";

const RISK_ORDER: Record<Risk, number> = { critical: 4, high: 3, medium: 2, low: 1 };

const maxRisk = (risks: Risk[]): Risk =>
  risks.reduce<Risk>((worst, risk) => (RISK_ORDER[risk] > RISK_ORDER[worst] ? risk : worst), "low");

interface Scored {
  risk: Risk;
  reasons: string[];
}

// Every rule states its own reason, so a score can always be traced back to the field that caused
// it. A route the reader cannot audit is a route they will learn to ignore.
const scoreDirectChange = (
  status: "changed" | "added" | "removed",
  details: ChangeDetail[],
  after: BehavioralSignature
): Scored => {
  const reasons: string[] = [];
  const risks: Risk[] = [];
  const detailOf = (field: string) => details.find((detail) => detail.field === field);

  if (status === "removed") {
    return { risk: "critical", reasons: ["the route no longer exists, so every caller of it breaks"] };
  }

  const auth = detailOf("auth_modes");
  if (auth?.removed.length) {
    risks.push("critical");
    reasons.push(`accepted auth modes dropped ${auth.removed.join(", ")}, which can lock callers out or widen access`);
  }
  if (auth?.added.length) {
    risks.push("high");
    reasons.push(`the route now also accepts ${auth.added.join(", ")}`);
  }

  const hooks = detailOf("hooks");
  if (hooks?.removed.some((hook) => hook.includes("verifyAuth"))) {
    risks.push("critical");
    reasons.push("an onRequest:verifyAuth hook was removed, so the route may no longer be authenticated");
  } else if (hooks?.removed.length) {
    risks.push("high");
    reasons.push(`lifecycle hooks removed: ${hooks.removed.join(", ")}`);
  }
  if (detailOf("hooks (reordered)")) {
    risks.push("critical");
    reasons.push("lifecycle hooks were reordered, which changes what runs before the handler");
  }

  for (const field of ["method", "url"] as const) {
    const detail = detailOf(field);
    if (detail) {
      risks.push("high");
      reasons.push(`${field} changed from ${detail.removed.join("") || "(none)"} to ${detail.added.join("") || "(none)"}, which breaks existing callers`);
    }
  }

  if (detailOf("response_schema")) {
    risks.push("high");
    reasons.push("the response schema changed, so clients parsing this response may break");
  }

  for (const field of ["params_fields", "body_fields", "query_fields"] as const) {
    const detail = detailOf(field);
    if (detail?.removed.length) {
      risks.push("high");
      reasons.push(`${field.replace("_fields", "")} field(s) removed: ${detail.removed.join(", ")}`);
    }
    if (detail?.added.length) {
      risks.push("low");
      reasons.push(`${field.replace("_fields", "")} field(s) added: ${detail.added.join(", ")}`);
    }
  }

  const rateLimit = detailOf("rate_limit");
  if (rateLimit) {
    const relaxed = rateLimit.removed.includes("writeLimit") && rateLimit.added.includes("readLimit");
    risks.push(relaxed ? "high" : "medium");
    reasons.push(
      `rate limit changed from ${rateLimit.removed.join("") || "(none)"} to ${rateLimit.added.join("") || "(none)"}` +
        (relaxed ? ", which relaxes a write path to read limits" : "")
    );
  }

  const serviceCalls = detailOf("service_calls");
  if (serviceCalls?.added.length) {
    risks.push("medium");
    reasons.push(`the handler now calls ${serviceCalls.added.join(", ")}`);
  }
  if (serviceCalls?.removed.length) {
    risks.push("high");
    reasons.push(`the handler no longer calls ${serviceCalls.removed.join(", ")}`);
  }

  const cross = detailOf("cross_module_deps");
  if (cross?.added.length) {
    risks.push("medium");
    reasons.push(`new dependencies on ${[...new Set(cross.added.map((dep) => dep.split(":")[0]))].join(", ")}`);
  }

  if (status === "added") {
    risks.push("medium");
    reasons.push("this is a new public endpoint, so it needs auth, validation and rate-limit review");
  }

  if (after.file.startsWith("src/ee/")) {
    risks.push("high");
    reasons.push("the route is enterprise-gated, so a regression is licence-visible");
  }

  if (!reasons.length) reasons.push("the signature moved without any field this analyzer scores");
  return { risk: maxRisk(risks.length ? risks : ["low"]), reasons };
};

// ---------------------------------------------------------------------------
// Impact model
// ---------------------------------------------------------------------------

type ImpactKind = "direct" | "indirect_di" | "indirect_graph";

interface RouteImpact {
  route: string;
  method: string;
  url: string;
  file: string;
  feature: string;
  operation_id: string;
  kind: ImpactKind;
  status?: "changed" | "added" | "removed";
  risk: Risk;
  reasons: string[];
  hash_before?: string;
  hash_after?: string;
  details?: ChangeDetail[];
  service_key?: string;
  service_methods?: string[];
  precision?: "method" | "module";
  depth?: number;
  chain?: string[];
  evidence?: string[];
}

interface WideImpact {
  reason: string;
  route_count: number;
  route_file_count: number;
  subsystems: { community: string; routes: number }[];
}

interface FileImpact {
  file: string;
  community: Community | null;
  service_keys: string[];
  direct: RouteImpact[];
  indirect: RouteImpact[];
  wide?: WideImpact;
  focus?: ChangeFocus;
  // Routes on the same service key that call a method this change did not touch. Reported as a
  // count, because the point of narrowing is not to print them.
  module_only_routes?: number;
  narrowing_notes?: string[];
}

interface ManifestView {
  routesByFile: Map<string, { route: string; signature: BehavioralSignature }[]>;
  routesByServiceKey: Map<string, { route: string; signature: BehavioralSignature }[]>;
  routeFiles: Set<string>;
}

const buildManifestView = (manifest: Manifest): ManifestView => {
  const routesByFile = new Map<string, { route: string; signature: BehavioralSignature }[]>();
  const routesByServiceKey = new Map<string, { route: string; signature: BehavioralSignature }[]>();

  for (const [route, signature] of Object.entries(manifest.routes ?? {})) {
    const entry = { route, signature };

    const byFile = routesByFile.get(signature.file);
    if (byFile) byFile.push(entry);
    else routesByFile.set(signature.file, [entry]);

    for (const key of new Set(signature.service_calls.map((call) => call.split(".")[0]))) {
      const byKey = routesByServiceKey.get(key);
      if (byKey) byKey.push(entry);
      else routesByServiceKey.set(key, [entry]);
    }
  }

  return { routesByFile, routesByServiceKey, routeFiles: new Set(routesByFile.keys()) };
};

const subsystemBreakdown = (
  routes: { file: string; feature: string }[],
  graph: GraphIndex | null
): { community: string; routes: number }[] => {
  const counts = new Map<string, number>();
  for (const route of routes) {
    const community = graph?.communityOfFile(route.file);
    const name = community?.name || route.feature;
    counts.set(name, (counts.get(name) ?? 0) + 1);
  }
  return [...counts.entries()]
    .sort((a, b) => b[1] - a[1] || a[0].localeCompare(b[0]))
    .slice(0, 6)
    .map(([community, routes]) => ({ community, routes }));
};

const toImpact = (
  entry: { route: string; signature: BehavioralSignature },
  kind: ImpactKind,
  scored: Scored,
  extra: Partial<RouteImpact> = {}
): RouteImpact => ({
  route: entry.route,
  method: entry.signature.method,
  url: entry.signature.url,
  file: entry.signature.file,
  feature: entry.signature.feature,
  operation_id: entry.signature.operation_id,
  kind,
  risk: scored.risk,
  reasons: scored.reasons,
  ...extra
});

// ---------------------------------------------------------------------------
// Analysis
// ---------------------------------------------------------------------------

interface Options {
  wideThreshold: number;
  maxDepth: number;
}

// The head revision, never the working tree: the analyzer runs on a checkout that does not contain
// an open pull request's commits, so its line numbers would land in the wrong function. A file the
// head does not have (a deletion) simply gets no focus and keeps file-level reach.
const buildFocuses = (report: DiffReport, files: string[]): Map<string, ChangeFocus> => {
  const focuses = new Map<string, ChangeFocus>();
  const hunks = report.meta?.changed_hunks;
  const head = report.meta?.head;
  if (!hunks || !head) return focuses;

  for (const file of files) {
    const ranges = hunks[file];
    if (!ranges?.length) continue;
    const text = readAtRevision(head, file);
    if (!text) continue;
    focuses.set(file, focusChange(file, text, ranges));
  }

  return focuses;
};

interface KeyNarrowing {
  methods?: FocusMethod[];
  reason?: string;
}

// Decided per service key, once, before any file is analysed - never per changed file. Two reasons:
//
//   - Soundness. Narrowing to the methods that changed in the bound module file is only honest if
//     that file is the ONLY changed file mapping to the key. If a dal, fns or queue file in the
//     same module also changed, a route calling an untouched service method can still change
//     behaviour through it, and excluding that route would be a false negative.
//   - Determinism. Changed files are analysed in sorted order and the first one to claim a route
//     wins, so a per-file decision let audit-report-dal.ts claim a route at module precision
//     before audit-report-service.ts could claim it at method precision. Same input, worse answer,
//     for no reason other than the alphabet.
const buildKeyNarrowing = (files: string[], di: DiBridge, focuses: Map<string, ChangeFocus>): Map<string, KeyNarrowing> => {
  const filesByKey = new Map<string, string[]>();
  for (const file of files) {
    for (const key of di.keysForFile(file)) {
      const bucket = filesByKey.get(key);
      if (bucket) bucket.push(file);
      else filesByKey.set(key, [file]);
    }
  }

  const narrowing = new Map<string, KeyNarrowing>();
  const shortName = (file: string): string => file.split("/").pop() ?? file;

  for (const [key, changed] of filesByKey) {
    const bound = di.byKey.get(key)?.moduleFile;
    if (!bound) continue;

    const focus = bound ? focuses.get(bound) : undefined;
    if (focus) focus.di_bound = true;

    if (!changed.includes(bound)) {
      narrowing.set(key, {
        reason:
          `${capped(changed.map(shortName), 3)} changed, which the service module uses rather than the file the key is ` +
          `bound to, so its callers cannot be resolved to methods`
      });
      continue;
    }
    if (changed.length > 1) {
      narrowing.set(key, {
        reason:
          `${capped(changed.filter((file) => file !== bound).map(shortName), 3)} in the same module also changed, and a ` +
          `route calling an untouched method can still change behaviour through those`
      });
      continue;
    }
    if (!focus) continue;
    if (!focus.narrowed) {
      narrowing.set(key, { reason: focus.reason });
      continue;
    }

    narrowing.set(key, { methods: focus.methods });
  }

  return narrowing;
};

const hasAuthorizationChange = (focus: ChangeFocus): boolean =>
  focus.categories.some((category) => category.category === AUTHORIZATION_CATEGORY);

const authorizationMethodsOf = (focus: ChangeFocus): string[] =>
  focus.methods
    .filter((method) => method.categories.some((category) => category.category === AUTHORIZATION_CATEGORY))
    .map((method) => method.name);

const analyzeFile = (
  file: string,
  view: ManifestView,
  di: DiBridge,
  graph: GraphIndex | null,
  directByFile: Map<string, RouteImpact[]>,
  focus: ChangeFocus | undefined,
  narrowing: Map<string, KeyNarrowing>,
  options: Options
): FileImpact => {
  const impact: FileImpact = {
    file,
    community: graph?.communityOfFile(file) ?? null,
    service_keys: di.keysForFile(file),
    direct: directByFile.get(file) ?? [],
    indirect: [],
    focus
  };

  const claimed = new Set(impact.direct.map((route) => route.route));
  const candidates: RouteImpact[] = [];
  const notes = new Set<string>();
  let moduleOnly = 0;

  // 1. DI reach. A service module's routes are invisible to the import graph, so this is the only
  //    path that finds them.
  //
  //    Narrowed to the changed methods when the changed file is the module the key is bound to and
  //    ./method-index.ts could resolve every hunk. Anything else (a dal or fns file in the same
  //    module, a hunk at module scope, an unresolvable helper) keeps the whole-key reach, because
  //    then the change really can surface through any method.
  for (const key of impact.service_keys) {
    const decision = narrowing.get(key);
    const narrowed = decision?.methods ?? null;
    const changedFor = new Map(narrowed?.map((method) => [method.name, method]) ?? []);
    if (!narrowed && decision?.reason) notes.add(decision.reason);

    for (const entry of view.routesByServiceKey.get(key) ?? []) {
      if (claimed.has(entry.route)) continue;

      if (narrowed) {
        const called = [...new Set(entry.signature.service_calls)]
          .filter((call) => call.startsWith(`${key}.`))
          .map((call) => call.slice(key.length + 1))
          .filter((method) => changedFor.has(method));

        if (!called.length) {
          moduleOnly += 1;
          continue;
        }

        const categories = called.flatMap((method) => changedFor.get(method)?.categories ?? []);
        const authorization = categories.find((category) => category.category === AUTHORIZATION_CATEGORY);
        const labels = [...new Set(categories.map((category) => category.label))];

        claimed.add(entry.route);
        candidates.push(
          toImpact(entry, "indirect_di", {
            risk: authorization ? "high" : "medium",
            reasons: [
              `this route executes ${called.map((method) => `server.services.${key}.${method}`).join(", ")}, which this change edits` +
                (labels.length ? ` (${labels.join("; ")})` : "") +
                " - its own signature did not move, so the gate cannot see this"
            ]
          }, { service_key: key, service_methods: called.sort(), precision: "method" })
        );
        continue;
      }

      claimed.add(entry.route);
      candidates.push(
        toImpact(entry, "indirect_di", {
          risk: "medium",
          reasons: [
            `this route calls server.services.${key}, which is wired to the changed module - its signature did not move, so the gate cannot see this`
          ]
        }, { service_key: key, precision: "module" })
      );
    }
  }

  if (moduleOnly) impact.module_only_routes = moduleOnly;
  if (notes.size) impact.narrowing_notes = [...notes];

  // 2. Graph reach, for everything the DI bridge does not cover (lib, helpers, plugins).
  if (graph) {
    const closure = graph.reverseClosure(file, options.maxDepth);
    for (const [reachedFile, entry] of closure) {
      if (!view.routeFiles.has(reachedFile)) continue;
      // routes/index.ts constructs every service, so it reaches all of them. It also happens to
      // declare one route (/api/status), which would otherwise be reported as impacted by every
      // service change in the repo. The edge is the wiring, not a dependency of that route.
      if (reachedFile === ROUTES_INDEX && file !== ROUTES_INDEX) continue;
      const chain = graph.chainTo(reachedFile, closure, file);
      const evidence: string[] = [];
      for (let i = 0; i < chain.length - 1; i += 1) {
        const [edge] = graph.edgesBetween(chain[i], chain[i + 1]);
        if (edge) evidence.push(`${edge.from}${edge.location ? `:${edge.location}` : ""} ${edge.relation} ${edge.to}`);
      }

      for (const route of view.routesByFile.get(reachedFile) ?? []) {
        if (claimed.has(route.route)) continue;
        claimed.add(route.route);
        candidates.push(
          toImpact(route, "indirect_graph", {
            risk: entry.depth === 1 ? "medium" : "low",
            reasons: [
              `its route file reaches the changed file in ${entry.depth} import hop${entry.depth === 1 ? "" : "s"}`
            ]
          }, { depth: entry.depth, chain, evidence })
        );
      }
    }
  }

  // A foundational file reaches most of the API. Enumerating that tells the reader nothing they
  // did not already know, and buries the changes that matter, so past the threshold it collapses
  // to a count plus the subsystems involved.
  const reachedFiles = new Set(candidates.map((route) => route.file));
  if (candidates.length > options.wideThreshold) {
    impact.wide = {
      reason:
        impact.service_keys.length && candidates.some((route) => route.kind === "indirect_di")
          ? `service key(s) ${impact.service_keys.join(", ")} are called by ${candidates.length} routes`
          : `${candidates.length} routes reach this file within ${options.maxDepth} import hops`,
      route_count: candidates.length,
      route_file_count: reachedFiles.size,
      subsystems: subsystemBreakdown(candidates, graph)
    };
  } else {
    impact.indirect = candidates.sort((a, b) => a.route.localeCompare(b.route));
  }

  return impact;
};

// ---------------------------------------------------------------------------
// Project resolution
// ---------------------------------------------------------------------------

interface ResolvedProject {
  id: string;
  name: string;
  source: "registry" | "router" | "community" | "unowned";
  matched_by?: string;
  definition?: ProjectDef;
}

const titleCase = (value: string): string =>
  value
    .split(/[-/]/)
    .filter(Boolean)
    .map((word) => word[0].toUpperCase() + word.slice(1))
    .join(" ");

// Graphify's community names are good for service modules ("Alerting Module Core", "PAM Accounts
// & Rotation") and unreliable for route files, because Leiden groups routers by their shared
// schema and rate-limit imports rather than by domain - which is how insights-router.ts ends up
// in a community named after ACME. A router names its own domain, so for route files that beats
// the community every time, and it is stable across graphify runs.
const routerProject = (file: string): { id: string; name: string } | null => {
  if (!file.includes("/routes/")) return null;

  const stem = path.posix.basename(file).replace(/\.tsx?$/, "").replace(/-(router|routers|endpoints)$/, "");
  if (stem === "index") {
    const segments = path.posix.dirname(file).split("/").slice(-2).join("/");
    return { id: `router:${segments}`, name: titleCase(segments) };
  }
  return { id: `router:${stem}`, name: titleCase(stem) };
};

const resolveProject = (impact: FileImpact, registry: ProjectRegistry | null): ResolvedProject => {
  for (const [id, definition] of Object.entries(registry?.projects ?? {})) {
    if (definition.path_globs?.some((pattern) => matchesGlob(impact.file, pattern))) {
      return { id, name: definition.name, source: "registry", matched_by: "path_globs", definition };
    }
  }
  for (const [id, definition] of Object.entries(registry?.projects ?? {})) {
    if (definition.service_keys?.some((key) => impact.service_keys.includes(key))) {
      return { id, name: definition.name, source: "registry", matched_by: "service_keys", definition };
    }
  }
  for (const [id, definition] of Object.entries(registry?.projects ?? {})) {
    if (impact.community && definition.communities?.includes(impact.community.name)) {
      return { id, name: definition.name, source: "registry", matched_by: "communities", definition };
    }
  }

  const router = routerProject(impact.file);
  if (router) {
    return { id: router.id, name: router.name, source: "router", matched_by: "the router file's own name" };
  }

  if (impact.community) {
    return {
      id: `community:${impact.community.id}`,
      name: impact.community.name || `Community ${impact.community.id}`,
      source: "community",
      matched_by: "graph community of the changed file"
    };
  }

  return { id: "unowned", name: "Unowned", source: "unowned" };
};

// ---------------------------------------------------------------------------
// Narrative
// ---------------------------------------------------------------------------

const narrateDirect = (route: RouteImpact, project: ResolvedProject): string => {
  const paragraphs: string[] = [];

  if (route.status === "changed") {
    paragraphs.push(
      `\`${route.method} ${route.url}\` in \`${route.file}\` changed behaviour: its signature hash moved ` +
        `from \`${route.hash_before}\` to \`${route.hash_after}\`.`
    );
  } else if (route.status === "added") {
    paragraphs.push(`\`${route.method} ${route.url}\` is a new endpoint in \`${route.file}\`.`);
  } else {
    paragraphs.push(`\`${route.method} ${route.url}\` was removed from \`${route.file}\`.`);
  }

  paragraphs.push(route.reasons.map((reason) => reason[0].toUpperCase() + reason.slice(1)).join(". ") + ".");
  paragraphs.push(`This lands in "${project.name}", matched by ${project.matched_by}.`);

  return paragraphs.join("\n\n");
};

const narrateIndirect = (route: RouteImpact): string => {
  if (route.kind === "indirect_di") {
    return (
      `\`${route.method} ${route.url}\` (\`${route.file}\`) calls \`server.services.${route.service_key}\`. ` +
      `The changed file is part of that service module, so this route's behaviour can move even though its ` +
      `own text - and therefore its signature hash - did not.`
    );
  }
  const trace = route.evidence?.length ? ` Path: ${route.evidence.join("; ")}.` : "";
  return (
    `\`${route.method} ${route.url}\` (\`${route.file}\`) reaches the changed file in ${route.depth} import ` +
    `hop${route.depth === 1 ? "" : "s"}.${trace}`
  );
};

// ---------------------------------------------------------------------------
// Action items
// ---------------------------------------------------------------------------

interface ActionItem {
  priority: Risk;
  action: string;
  assignee?: string;
}

const buildActionItems = (
  project: ProjectOutput,
  definition: ProjectDef | undefined,
  now: Date
): ActionItem[] => {
  const items: ActionItem[] = [];
  const owner = definition?.owner;

  const authChanges = project.changes.filter((route) =>
    route.reasons.some((reason) => reason.includes("auth mode") || reason.includes("verifyAuth") || reason.includes("hooks"))
  );
  if (authChanges.length) {
    items.push({
      priority: "critical",
      action: `Review the auth surface on ${authChanges.map((route) => `${route.method} ${route.url}`).join(", ")} before merging.`,
      assignee: owner
    });
  }

  const contractChanges = project.changes.filter((route) =>
    route.reasons.some((reason) => reason.includes("breaks existing callers") || reason.includes("clients parsing"))
  );
  if (contractChanges.length) {
    items.push({
      priority: "high",
      action:
        `${contractChanges.length} route(s) changed their request or response contract. Adding an optional field is safe; ` +
        `renaming one, tightening validation or changing a status code is not - version the route instead.`,
      assignee: owner
    });
  }

  const routeList = (routes: RouteImpact[], limit = 5): string =>
    `${routes.slice(0, limit).map((route) => `${route.method} ${route.url}`).join(", ")}${routes.length > limit ? `, and ${routes.length - limit} more` : ""}`;

  // Authorization first, and named as the finding rather than buried in a coverage nudge. A
  // permission change moves no signature, so this is the one thing in the report that the gate
  // alone would have reported as "no behaviour change".
  const authorizationFiles = project.changed_code.filter(hasAuthorizationChange);
  if (authorizationFiles.length) {
    const methods = [...new Set(authorizationFiles.flatMap(authorizationMethodsOf))];
    const executing = project.impacted_routes.indirect_di.filter((route) =>
      route.service_methods?.some((method) => methods.includes(method))
    );
    const where = methods.length
      ? `in ${capped(methods.map((method) => `\`${method}\``), 5)}`
      : `in ${capped(authorizationFiles.map((focus) => `\`${focus.file.split("/").pop()}\``), 3)}`;

    items.push({
      priority: "high",
      action:
        `An access-control decision changed ${where}. Exercise both the allow and the deny path` +
        `${executing.length ? ` on ${routeList(executing)}` : ""}: a permission change moves no route signature, so no ` +
        `other check in this report can catch a regression.`,
      assignee: owner
    });
  }

  const executes = project.impacted_routes.indirect_di.filter((route) => route.precision === "method");
  const moduleWide = project.impacted_routes.indirect_di.filter((route) => route.precision !== "method");

  if (executes.length) {
    const untouched = project.module_only_routes
      ? ` The other ${project.module_only_routes} route(s) on this service key call methods this change does not touch.`
      : "";
    items.push({
      priority: "medium",
      action:
        (executes.length === 1
          ? `${routeList(executes)} executes changed code with no signature change of its own, so the behaviour gate is ` +
            `blind to it. Confirm it has test coverage.`
          : `${executes.length} routes execute changed code with no signature change of their own, so the behaviour gate ` +
            `is blind to them. Confirm coverage on ${routeList(executes)}.`) + untouched,
      assignee: owner
    });
  }

  if (moduleWide.length) {
    // Why the list is this wide matters as much as the list: a reader who knows it could not be
    // narrowed treats it as a reach set, and a reader who does not treats it as an impact set.
    const why = project.narrowing_notes.length ? ` Not narrowed to a method: ${project.narrowing_notes[0]}.` : "";

    items.push({
      priority: "medium",
      action:
        `${moduleWide.length} route(s) call into the changed service module but have no signature change, so the behaviour ` +
        `gate is blind to them. Confirm they have test coverage: ${routeList(moduleWide)}.${why}`,
      assignee: owner
    });
  }

  if (definition?.slack) {
    items.push({
      priority: "medium",
      action: `Notify ${definition.team ? `${definition.team} ` : ""}in ${definition.slack}.`,
      assignee: owner
    });
  }

  if (definition?.launch_date) {
    const launch = new Date(`${definition.launch_date}T00:00:00Z`);
    const days = Math.ceil((launch.getTime() - now.getTime()) / 86_400_000);
    if (days > 0 && days <= 14) {
      items.push({
        priority: "high",
        action: `This project launches in ${days} day(s) (${definition.launch_date}); behavioural changes this close to launch need extra scrutiny.`,
        assignee: owner
      });
    }
  }

  return items;
};

// ---------------------------------------------------------------------------
// Assembly
// ---------------------------------------------------------------------------

interface ProjectOutput {
  project_id: string;
  project_name: string;
  source: ResolvedProject["source"];
  matched_by?: string;
  owner?: string;
  team?: string;
  slack?: string;
  jira?: string;
  status?: string;
  launch_date?: string;
  max_risk: Risk;
  headline: string;
  changed_files: string[];
  changed_code: ChangeFocus[];
  module_only_routes: number;
  narrowing_notes: string[];
  impacted_routes: {
    direct: RouteImpact[];
    indirect_di: RouteImpact[];
    indirect_graph: RouteImpact[];
  };
  changes: RouteImpact[];
  narratives: { route: string; kind: ImpactKind; narrative: string }[];
  wide_impact: (WideImpact & { file: string })[];
  action_items: ActionItem[];
}

interface Analysis {
  meta: Record<string, unknown>;
  summary: Record<string, unknown>;
  affected_projects: ProjectOutput[];
  wide_impact_files: (WideImpact & { file: string; project: string })[];
  no_route_impact: { file: string; project: string; reason: string }[];
  unowned_changes: { file: string; reason: string }[];
  skipped_files: { file: string; reason: string }[];
  unaffected_projects?: { project_id: string; project_name: string }[];
}

const METHOD_LIST_LIMIT = 6;

const capped = (items: string[], limit: number): string =>
  `${items.slice(0, limit).join(", ")}${items.length > limit ? `, and ${items.length - limit} more` : ""}`;

const methodSummary = (focus: ChangeFocus, withFile = true): string => {
  const prefix = withFile ? `${focus.file.split("/").pop() ?? focus.file}: ` : "";
  const labels = focus.categories.map((category) => category.label);
  const notes = focus.notes.length ? ` (${focus.notes.join("; ")})` : "";
  // A refusal is only informative for the file a service key is bound to. On a dal or fns file
  // there is no factory to resolve against and saying so on every one of them is noise.
  const refusal = !focus.narrowed && focus.di_bound && focus.reason ? ` (not narrowed: ${focus.reason})` : "";

  if (!focus.methods.length) {
    return `${prefix}${labels.join("; ") || focus.reason || "no method resolved"}${notes}`;
  }

  const methods = focus.methods.map((method) => {
    const via = method.via.length ? ` (via ${capped(method.via, 3)})` : "";
    const own = method.categories.map((category) => category.label);
    return `${method.name}${via}${own.length ? ` [${own.join("; ")}]` : ""}`;
  });

  return `${prefix}${capped(methods, METHOD_LIST_LIMIT)}${notes}${refusal}`;
};

const buildHeadline = (project: ProjectOutput): string => {
  const parts: string[] = [];
  const direct = project.impacted_routes.direct;
  if (direct.length) {
    const counts = { changed: 0, added: 0, removed: 0 };
    for (const route of direct) counts[route.status ?? "changed"] += 1;
    const segments = [
      counts.changed ? `${counts.changed} changed` : "",
      counts.added ? `${counts.added} new` : "",
      counts.removed ? `${counts.removed} removed` : ""
    ].filter(Boolean);
    parts.push(`${segments.join(", ")} route${direct.length === 1 ? "" : "s"}`);
  }

  const executes = project.impacted_routes.indirect_di.filter((route) => route.precision === "method").length;
  const reached =
    project.impacted_routes.indirect_di.filter((route) => route.precision !== "method").length +
    project.impacted_routes.indirect_graph.length;

  if (executes) parts.push(`${executes} route${executes === 1 ? " executes" : "s execute"} the changed code`);
  if (reached) parts.push(`${reached} route${reached === 1 ? "" : "s"} reached indirectly with no signature change`);
  if (project.module_only_routes) {
    parts.push(`${project.module_only_routes} on the same service key call methods this change does not touch`);
  }
  if (project.wide_impact.length) {
    parts.push(`${project.wide_impact.length} foundational file${project.wide_impact.length === 1 ? "" : "s"} with repo-wide reach`);
  }

  return parts.length ? `${parts.join("; ")}.` : "No route-level impact detected.";
};

const analyze = (
  report: DiffReport,
  manifest: Manifest,
  config: BehaviorConfig,
  graph: GraphIndex | null,
  di: DiBridge,
  registry: ProjectRegistry | null,
  options: Options
): Analysis => {
  const view = buildManifestView(manifest);
  const now = new Date();

  const directByFile = new Map<string, RouteImpact[]>();
  const push = (file: string, impact: RouteImpact) => {
    const bucket = directByFile.get(file);
    if (bucket) bucket.push(impact);
    else directByFile.set(file, [impact]);
  };

  for (const item of report.changed) {
    const scored = scoreDirectChange("changed", item.details, item.after);
    push(
      item.after.file,
      toImpact({ route: item.route, signature: item.after }, "direct", scored, {
        status: "changed",
        hash_before: item.before.hash,
        hash_after: item.after.hash,
        details: item.details
      })
    );
  }
  for (const item of report.added) {
    const scored = scoreDirectChange("added", [], item.signature);
    push(item.signature.file, toImpact(item, "direct", scored, { status: "added", hash_after: item.signature.hash }));
  }
  for (const item of report.removed) {
    const scored = scoreDirectChange("removed", [], item.signature);
    push(item.signature.file, toImpact(item, "direct", scored, { status: "removed", hash_before: item.signature.hash }));
  }

  // A changed route file that the gate found nothing in still needs analysing (its imports may
  // have moved), so the union is changed_files plus any file carrying a direct change - the latter
  // covers a report produced without meta, e.g. by an older run.
  const changedFiles = [...new Set([...(report.meta?.changed_files ?? []), ...directByFile.keys()])].sort();

  const skipped: Analysis["skipped_files"] = [];
  const analysable: string[] = [];
  for (const file of changedFiles) {
    if (isExcludedPath(file, config)) {
      skipped.push({ file, reason: "matches excluded_path_globs in .behavior-config.json" });
      continue;
    }
    analysable.push(file);
  }

  const focuses = buildFocuses(report, analysable);
  const narrowing = buildKeyNarrowing(analysable, di, focuses);

  const byProject = new Map<string, ProjectOutput>();
  const seenByProject = new Map<string, Set<string>>();
  const definitions = new Map<string, ProjectDef | undefined>();
  const unowned: Analysis["unowned_changes"] = [];
  const noRouteImpact: Analysis["no_route_impact"] = [];
  const wideFiles: Analysis["wide_impact_files"] = [];

  for (const file of analysable) {
    const impact = analyzeFile(file, view, di, graph, directByFile, focuses.get(file), narrowing, options);
    const project = resolveProject(impact, registry);

    // A file with no reachable route is reported, but not as an affected project - otherwise a
    // project appears in the rollup whose entire headline is "no impact detected", which is worse
    // than not listing it.
    if (!impact.direct.length && !impact.indirect.length && !impact.wide) {
      // Narrowing turns this into a real finding rather than a shrug: the change is wired to the
      // API, and no route on it calls what changed. Whatever exercises this code is not HTTP.
      const changedMethods = capped((impact.focus?.methods ?? []).map((method) => method.name), 4);
      const reason = impact.module_only_routes
        ? `wired to server.services.${impact.service_keys.join(", ")}, but no route calls the changed method(s) ` +
          `${changedMethods || "(none resolved)"} - ${impact.module_only_routes} route(s) on that key call other methods, ` +
          `so this change is reached from a queue worker, a cron job or another service rather than a request`
        : `${changedMethods ? `${changedMethods} changed; ` : ""}no route reaches it within ${options.maxDepth} ` +
          `import hops and it is not wired to a service key`;

      if (project.source === "unowned") {
        unowned.push({ file, reason: "no graph community, no service wiring, and no route reaches it" });
      } else {
        noRouteImpact.push({ file, project: project.name, reason });
      }
      continue;
    }

    let output = byProject.get(project.id);
    if (!output) {
      output = {
        project_id: project.id,
        project_name: project.name,
        source: project.source,
        matched_by: project.matched_by,
        owner: project.definition?.owner,
        team: project.definition?.team,
        slack: project.definition?.slack,
        jira: project.definition?.jira,
        status: project.definition?.status,
        launch_date: project.definition?.launch_date,
        max_risk: "low",
        headline: "",
        changed_files: [],
        changed_code: [],
        module_only_routes: 0,
        narrowing_notes: [],
        impacted_routes: { direct: [], indirect_di: [], indirect_graph: [] },
        changes: [],
        narratives: [],
        wide_impact: [],
        action_items: []
      };
      byProject.set(project.id, output);
      definitions.set(project.id, project.definition);
    }

    output.changed_files.push(file);
    output.module_only_routes += impact.module_only_routes ?? 0;
    for (const note of impact.narrowing_notes ?? []) {
      if (!output.narrowing_notes.includes(note)) output.narrowing_notes.push(note);
    }
    // A focus with neither a resolved method nor a classified line has nothing a reader can act
    // on, and every route file would otherwise contribute one "no factory found" line.
    if (impact.focus && (impact.focus.methods.length || impact.focus.categories.length)) {
      output.changed_code.push(impact.focus);
    }

    // Two files in the same service module both reach that service's routes, so without this the
    // route is listed once per changed file. Attribution is per project, not per file: a route
    // that two different projects reach is still worth reporting to both.
    const seen = seenByProject.get(project.id) ?? new Set<string>();
    seenByProject.set(project.id, seen);

    for (const route of impact.direct) {
      if (seen.has(route.route)) continue;
      seen.add(route.route);
      output.impacted_routes.direct.push(route);
      output.changes.push(route);
      output.narratives.push({ route: route.route, kind: route.kind, narrative: narrateDirect(route, project) });
    }
    for (const route of impact.indirect) {
      if (seen.has(route.route)) continue;
      seen.add(route.route);
      if (route.kind === "indirect_di") output.impacted_routes.indirect_di.push(route);
      else output.impacted_routes.indirect_graph.push(route);
      output.narratives.push({ route: route.route, kind: route.kind, narrative: narrateIndirect(route) });
    }

    if (impact.wide) {
      const entry = { ...impact.wide, file };
      output.wide_impact.push(entry);
      wideFiles.push({ ...entry, project: project.name });
    }
  }

  for (const output of byProject.values()) {
    const risks: Risk[] = [
      ...output.impacted_routes.direct.map((route) => route.risk),
      ...output.impacted_routes.indirect_di.map((route) => route.risk),
      ...output.impacted_routes.indirect_graph.map((route) => route.risk),
      // Reaching most of the API is itself worth a look, even when the edit looks trivial.
      ...output.wide_impact.map((): Risk => "medium"),
      // An access decision changing is the case both halves of this tool are blind to: no route
      // signature moves, and the route list looks the same as any other service edit. Lifting the
      // project (not every route on it) is what puts it at the top of the report.
      ...output.changed_code.filter(hasAuthorizationChange).map((): Risk => "high")
    ];
    output.max_risk = maxRisk(risks.length ? risks : ["low"]);
    output.changed_files.sort();
    output.headline = buildHeadline(output);
    output.action_items = buildActionItems(output, definitions.get(output.project_id), now);
  }

  const projects = [...byProject.values()].sort(
    (a, b) =>
      RISK_ORDER[b.max_risk] - RISK_ORDER[a.max_risk] ||
      b.impacted_routes.direct.length - a.impacted_routes.direct.length ||
      a.project_name.localeCompare(b.project_name)
  );

  const totals = projects.reduce(
    (acc, project) => ({
      direct: acc.direct + project.impacted_routes.direct.length,
      indirect: acc.indirect + project.impacted_routes.indirect_di.length + project.impacted_routes.indirect_graph.length,
      executing: acc.executing + project.impacted_routes.indirect_di.filter((route) => route.precision === "method").length,
      moduleOnly: acc.moduleOnly + project.module_only_routes
    }),
    { direct: 0, indirect: 0, executing: 0, moduleOnly: 0 }
  );

  const refusals = [...focuses.values()]
    .filter((focus) => !focus.narrowed)
    .map((focus) => ({ file: focus.file, reason: focus.reason ?? "" }));

  const analysis: Analysis = {
    meta: {
      generated_at: now.toISOString(),
      report: { scope: report.scope, base: report.meta?.base, head: report.meta?.head, pr: report.meta?.pr },
      manifest: { revision: manifest._meta?.revision, route_count: manifest._meta?.route_count },
      graph: graph ? { commit: graph.commit, nodes: graph.nodeCount, edges: graph.edgeCount } : null,
      di_bridge: { service_keys: di.byKey.size, unresolved: di.unresolved },
      narrowing: {
        available: Boolean(report.meta?.changed_hunks && report.meta?.head),
        files_with_hunks: focuses.size,
        narrowed: focuses.size - refusals.length,
        refused: refusals,
        // Files resolving to methods is not the same as reach being narrowed: the key is only
        // narrowed when the bound module file is the sole changed file mapping to it.
        keys_considered: narrowing.size,
        keys_narrowed: [...narrowing.values()].filter((decision) => decision.methods).length,
        keys_refused: [...narrowing.entries()]
          .filter(([, decision]) => !decision.methods)
          .map(([key, decision]) => ({ key, reason: decision.reason ?? "" }))
      },
      thresholds: options
    },
    summary: {
      changed_files: changedFiles.length,
      analysed_files: analysable.length,
      direct_routes: totals.direct,
      indirect_routes: totals.indirect,
      executing_routes: totals.executing,
      module_only_routes: totals.moduleOnly,
      wide_impact_files: wideFiles.length,
      projects_affected: projects.length,
      max_risk: projects.length ? projects[0].max_risk : "low"
    },
    affected_projects: projects,
    wide_impact_files: wideFiles,
    no_route_impact: noRouteImpact,
    unowned_changes: unowned,
    skipped_files: skipped
  };

  // Only meaningful against a real registry: listing the hundreds of graph communities a change
  // did not touch would be noise, not information.
  if (registry) {
    analysis.unaffected_projects = Object.entries(registry.projects)
      .filter(([id]) => !byProject.has(id))
      .map(([id, definition]) => ({ project_id: id, project_name: definition.name }));
  }

  return analysis;
};

// ---------------------------------------------------------------------------
// Rendering
// ---------------------------------------------------------------------------

const RISK_LABEL: Record<Risk, string> = { critical: "[!!!]", high: "[!!]", medium: "[!]", low: "[.]" };

const cell = (value: string): string => value.replace(/\|/g, "\\|");

const renderMarkdown = (analysis: Analysis): string => {
  const lines: string[] = ["## Project impact", ""];
  const meta = analysis.meta.report as { pr?: { slug: string; number: number }; base?: string; head?: string };

  if (meta.pr) lines.push(`Pull request \`${meta.pr.slug}#${meta.pr.number}\`.`);
  const executing = analysis.summary.executing_routes as number;
  const moduleOnly = analysis.summary.module_only_routes as number;
  lines.push(
    `${analysis.summary.analysed_files} changed file(s) analysed. ` +
      `${analysis.summary.direct_routes} route(s) changed signature, ` +
      `${analysis.summary.indirect_routes} more are reached indirectly and move no hash` +
      (executing ? `, ${executing} of which execute a changed method` : "") +
      `.` +
      (moduleOnly
        ? ` ${moduleOnly} further route(s) share a service key with the change but call methods it does not touch, and are not listed.`
        : ""),
    ""
  );

  if (!analysis.affected_projects.length) {
    lines.push("No project-level impact detected.", "");
    if (analysis.no_route_impact.length) {
      lines.push("**Changed files with no route reach**", "");
      for (const item of analysis.no_route_impact.slice(0, 10)) lines.push(`- \`${item.file}\` - ${item.reason}`);
      if (analysis.no_route_impact.length > 10) lines.push(`- ...and ${analysis.no_route_impact.length - 10} more`);
      lines.push("");
    }
    return lines.join("\n");
  }

  lines.push(
    "| Project | Risk | Changed routes | Indirect | Owner |",
    "| --- | --- | --- | --- | --- |"
  );
  for (const project of analysis.affected_projects) {
    const indirect = project.impacted_routes.indirect_di.length + project.impacted_routes.indirect_graph.length;
    lines.push(
      `| ${cell(project.project_name)} | ${project.max_risk} | ${project.impacted_routes.direct.length} | ${indirect} | ${cell(project.owner ?? "-")} |`
    );
  }
  lines.push("");

  for (const project of analysis.affected_projects) {
    lines.push(`<details><summary><b>${cell(project.project_name)}</b> - ${project.max_risk} - ${cell(project.headline)}</summary>`, "");

    if (project.action_items.length) {
      lines.push("**Actions**", "");
      for (const item of project.action_items) {
        lines.push(`- \`${item.priority}\` ${item.action}${item.assignee ? ` (${item.assignee})` : ""}`);
      }
      lines.push("");
    }

    if (project.changed_code.length) {
      lines.push("**Changed code**", "");
      for (const focus of project.changed_code) {
        lines.push(`- \`${focus.file}\` - ${cell(methodSummary(focus, false))}`);
        for (const category of focus.categories) lines.push(`  - ${category.label}: \`${cell(category.evidence)}\``);
      }
      lines.push("");
    }

    if (project.impacted_routes.direct.length) {
      lines.push("**Routes whose behaviour changed**", "");
      for (const route of project.impacted_routes.direct) {
        lines.push(`- \`${route.method} ${route.url}\` (${route.status}, ${route.risk}) - ${route.reasons.join("; ")}`);
      }
      lines.push("");
    }

    const indirect = [...project.impacted_routes.indirect_di, ...project.impacted_routes.indirect_graph];
    if (indirect.length) {
      lines.push("**Reached indirectly (no signature change - the behaviour gate cannot see these)**", "");
      for (const route of indirect.slice(0, 25)) {
        const how =
          route.precision === "method"
            ? `executes ${route.service_methods?.map((method) => `\`${route.service_key}.${method}\``).join(", ")}`
            : route.kind === "indirect_di"
              ? `via server.services.${route.service_key}`
              : `${route.depth} import hop(s)`;
        lines.push(`- \`${route.method} ${route.url}\` - ${how}`);
      }
      if (indirect.length > 25) lines.push(`- ...and ${indirect.length - 25} more`);
      if (project.module_only_routes) {
        lines.push(
          `- ${project.module_only_routes} route(s) on the same service key call methods this change does not touch, and are not listed`
        );
      }
      lines.push("");
    }

    if (project.wide_impact.length) {
      lines.push("**Foundational files (reach capped)**", "");
      for (const wide of project.wide_impact) {
        lines.push(`- \`${wide.file}\` - ${wide.reason}; subsystems: ${wide.subsystems.map((s) => `${s.community} (${s.routes})`).join(", ")}`);
      }
      lines.push("");
    }

    lines.push(`Changed files: ${project.changed_files.map((file) => `\`${file}\``).join(", ")}`, "", "</details>", "");
  }

  if (analysis.unowned_changes.length) {
    lines.push("**Unowned changes**", "");
    for (const item of analysis.unowned_changes) lines.push(`- \`${item.file}\` - ${item.reason}`);
    lines.push("");
  }

  return lines.join("\n");
};

const printSummary = (analysis: Analysis): void => {
  console.log("\n  Project Impact Analysis\n");

  // "No impact" is a claim, not an answer. What a reader needs is which file was analysed and what
  // stopped it reaching a route, or they cannot tell a genuinely internal change from a hole in
  // the tool's wiring.
  if (!analysis.affected_projects.length) {
    console.log("  No project-level impact detected.\n");
    for (const item of analysis.no_route_impact.slice(0, 8)) {
      console.log(`  [.] ${item.file}`);
      console.log(`      ${item.reason}`);
    }
    if (analysis.no_route_impact.length > 8) {
      console.log(`  [.] ...and ${analysis.no_route_impact.length - 8} more file(s)`);
    }
    if (analysis.no_route_impact.length) console.log("");
  }

  for (const project of analysis.affected_projects) {
    console.log(`  ${RISK_LABEL[project.max_risk]} ${project.project_name}`);
    console.log(`      ${project.headline}`);
    const features = [
      ...new Set(
        [
          ...project.impacted_routes.direct,
          ...project.impacted_routes.indirect_di,
          ...project.impacted_routes.indirect_graph
        ].map((route) => route.feature)
      )
    ].sort();
    for (const focus of project.changed_code.slice(0, 4)) console.log(`      changed code: ${methodSummary(focus)}`);
    if (project.changed_code.length > 4) {
      console.log(`      changed code: ...and ${project.changed_code.length - 4} more file(s)`);
    }
    if (features.length) console.log(`      features: ${features.join(", ")}`);
    if (project.owner || project.team) console.log(`      owner: ${project.owner ?? "-"} | team: ${project.team ?? "-"}`);
    for (const item of project.action_items) console.log(`      -> [${item.priority}] ${item.action}`);
    console.log("");
  }

  for (const wide of analysis.wide_impact_files) {
    console.log(`  [~] ${wide.file}: ${wide.reason} (not enumerated)`);
  }
  if (analysis.wide_impact_files.length) console.log("");

  const narrowing = (analysis.meta.narrowing ?? {}) as {
    available?: boolean;
    narrowed?: number;
    files_with_hunks?: number;
    keys_narrowed?: number;
    keys_considered?: number;
  };
  console.log(
    `  Summary: ${analysis.summary.direct_routes} route(s) changed, ${analysis.summary.indirect_routes} reached indirectly ` +
      `(${analysis.summary.executing_routes} executing a changed method), ` +
      `${analysis.summary.module_only_routes} untouched on the same service key(s), ` +
      `${analysis.summary.projects_affected} project(s) affected`
  );
  if (narrowing.available) {
    console.log(
      `  Method narrowing: ${narrowing.narrowed}/${narrowing.files_with_hunks} changed file(s) resolved to methods, ` +
        `${narrowing.keys_narrowed}/${narrowing.keys_considered} service key(s) narrowed`
    );
  } else {
    console.log(
      "  Method narrowing: unavailable (this report carries no changed_hunks; regenerate it with the current behavior:pr)"
    );
  }
};

// ---------------------------------------------------------------------------
// discover-projects
// ---------------------------------------------------------------------------

const commandDiscoverProjects = (graphPath: string, configPath: string, registryPath: string): void => {
  const config = loadConfig(configPath);
  const graph = loadGraphIndex(graphPath, config);
  if (!graph) fail(`No graph at '${graphPath}'. Run graphify first, or pass --graph.`);

  const di = loadDiBridge();

  // One project per community that owns a SERVICE module, seeded with the paths and service keys
  // that resolve to it. A human then fills in the metadata a graph cannot know.
  //
  // Route files are deliberately not scaffolded. Their communities are unreliable (Leiden groups
  // routers by shared schema imports, not by domain), and a glob wide enough to cover one -
  // src/ee/routes/v1/** - would then claim every router in that directory. Left out, they fall
  // through to the router-name derivation in the analyzer, which is both accurate and stable.
  const communities = new Map<string, { name: string; dirs: Set<string>; keys: Set<string> }>();

  const record = (file: string) => {
    const community = graph.communityOfFile(file);
    if (!community) return;
    const id = `community-${community.id}`;
    let entry = communities.get(id);
    if (!entry) {
      entry = { name: community.name || `Community ${community.id}`, dirs: new Set(), keys: new Set() };
      communities.set(id, entry);
    }
    entry.dirs.add(path.posix.dirname(file));
    for (const key of di.keysForFile(file)) entry.keys.add(key);
  };

  for (const binding of di.byKey.values()) record(binding.moduleFile);

  const slug = (name: string): string =>
    name
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-|-$/g, "") || "unnamed";

  const projects: Record<string, ProjectDef> = {};
  for (const [, entry] of [...communities.entries()].sort((a, b) => a[1].name.localeCompare(b[1].name))) {
    // Collapse sibling directories to their module root so the globs stay readable and keep
    // matching after a file is added.
    const roots = [...new Set([...entry.dirs].map((dir) => dir.split("/").slice(0, dir.startsWith("src/ee") || dir.startsWith("src/server") ? 4 : 3).join("/")))];
    projects[slug(entry.name)] = {
      name: entry.name,
      owner: "",
      team: "",
      slack: "",
      jira: "",
      status: "",
      launch_date: "",
      path_globs: roots.sort().map((root) => `${root}/**`),
      service_keys: [...entry.keys].sort(),
      communities: [entry.name]
    };
  }

  const output = {
    _notes: REGISTRY_NOTES,
    analysis: { wide_threshold: DEFAULT_WIDE_THRESHOLD, max_depth: DEFAULT_MAX_DEPTH },
    projects
  };

  writeFileSync(registryPath, `${JSON.stringify(output, null, 2)}\n`);
  console.log(
    `\n  Registry scaffold written to ${path.relative(BACKEND_ROOT, registryPath)}\n` +
      `    Projects:     ${Object.keys(projects).length} (one per graph community that owns backend source)\n` +
      `    Service keys: ${di.byKey.size} wired${di.unresolved.length ? `, ${di.unresolved.length} unresolved` : ""}\n\n` +
      `  Fill in owner / team / slack, delete what you do not want tracked, then commit it.\n` +
      `  Community names are regenerated on every graphify run - prefer path_globs for anything durable.\n`
  );
};

// ---------------------------------------------------------------------------
// CLI
// ---------------------------------------------------------------------------

const USAGE = `Usage: tsx ./scripts/graphs/project-analyzer.ts [command] [options]

Commands:
  analyze             (default) join a diff report with the graph and report per-project impact
  discover-projects   scaffold .behavior-projects.json from the graph and the DI wiring

Options:
  --report PATH       diff report from behavior:pr / behavior:diff (required for analyze)
  --manifest PATH     route manifest (default: backend/.behavior-manifest.json)
  --graph PATH        graph.json (default: ../graphify-out/graph.json)
  --config PATH       behavior config (default: backend/.behavior-config.json)
  --registry PATH     project registry (default: backend/.behavior-projects.json, optional)
  --output PATH       analysis JSON to write (default: backend/project-analysis.json)
  --markdown PATH     also write a pull-request-ready markdown summary
  --wide-threshold N  routes past which a file is reported as a count (default: ${DEFAULT_WIDE_THRESHOLD})
  --max-depth N       import hops to follow back from a changed file (default: ${DEFAULT_MAX_DEPTH})
  --ci                exit 1 when any project is critical or high risk
  -h, --help          show this message

Example:
  npm run behavior:pr -- --url 7638 --report /tmp/report.json
  npm run behavior:analyze -- --report /tmp/report.json --markdown /tmp/impact.md
`;

const positiveInt = (value: string | undefined, fallback: number, flag: string): number => {
  if (value === undefined) return fallback;
  const parsed = Number(value);
  if (!Number.isInteger(parsed) || parsed < 1) fail(`${flag} must be a positive integer, got '${value}'.`);
  return parsed;
};

const main = (): void => {
  const { values, positionals } = parseArgs({
    allowPositionals: true,
    options: {
      report: { type: "string" },
      manifest: { type: "string" },
      graph: { type: "string" },
      config: { type: "string" },
      registry: { type: "string" },
      output: { type: "string" },
      markdown: { type: "string" },
      "wide-threshold": { type: "string" },
      "max-depth": { type: "string" },
      ci: { type: "boolean", default: false },
      help: { type: "boolean", short: "h", default: false }
    }
  });

  if (values.help) {
    console.log(USAGE);
    process.exit(0);
  }

  const graphPath = path.resolve(values.graph ?? DEFAULT_GRAPH);
  const configPath = path.resolve(values.config ?? DEFAULT_CONFIG);
  const manifestPath = path.resolve(values.manifest ?? DEFAULT_MANIFEST);
  const registryPath = path.resolve(values.registry ?? DEFAULT_REGISTRY);

  const command = positionals[0] ?? "analyze";
  if (command === "discover-projects") {
    commandDiscoverProjects(graphPath, configPath, registryPath);
    return;
  }
  if (command !== "analyze") fail(`Unknown command '${command}'.\n${USAGE}`);

  if (!values.report) {
    fail(
      `Pass --report <path>, the JSON written by \`npm run behavior:pr -- --report <path>\`.\n` +
        `Without it there is no set of changed files to analyse.\n${USAGE}`
    );
  }
  const reportPath = path.resolve(values.report);
  if (!existsSync(reportPath)) fail(`No diff report at '${reportPath}'.`);
  if (!existsSync(manifestPath)) {
    fail(
      `No route manifest at '${path.relative(BACKEND_ROOT, manifestPath)}'.\n` +
        `Run \`npm run behavior:build\` first - the analyzer needs it to know which routes call which service.`
    );
  }

  const report = JSON.parse(readFileSync(reportPath, "utf-8")) as DiffReport;
  const manifest = JSON.parse(readFileSync(manifestPath, "utf-8")) as Manifest;
  const config = loadConfig(configPath);
  const registry = loadRegistry(registryPath);
  const graph = loadGraphIndex(graphPath, config);
  const di = loadDiBridge();

  if (!graph) {
    console.warn(
      `  warn: no graph at ${graphPath}. Service reach still works via the DI wiring, but ` +
        `library and helper changes cannot be traced and grouping falls back to unowned.`
    );
  }
  if (!report.meta?.changed_files?.length) {
    console.warn(
      "  warn: this report carries no changed_files list, so only routes whose signature moved are " +
        "analysed. Regenerate it with the current behavior:pr to get service-level reach."
    );
  }
  if (di.unresolved.length) {
    console.warn(
      `  warn: ${di.unresolved.length} service key(s) could not be resolved to a module ` +
        `(${di.unresolved.map((entry) => entry.key).join(", ")}); routes calling them will not be reported as indirectly impacted.`
    );
  }

  const options: Options = {
    wideThreshold: positiveInt(values["wide-threshold"], registry?.analysis?.wide_threshold ?? DEFAULT_WIDE_THRESHOLD, "--wide-threshold"),
    maxDepth: positiveInt(values["max-depth"], registry?.analysis?.max_depth ?? DEFAULT_MAX_DEPTH, "--max-depth")
  };

  const analysis = analyze(report, manifest, config, graph, di, registry, options);

  const outputPath = path.resolve(values.output ?? DEFAULT_OUTPUT);
  writeFileSync(outputPath, `${JSON.stringify(analysis, null, 2)}\n`);
  if (values.markdown) writeFileSync(path.resolve(values.markdown), renderMarkdown(analysis));

  printSummary(analysis);
  console.log(`  Written: ${path.relative(BACKEND_ROOT, outputPath)}${values.markdown ? ` and ${values.markdown}` : ""}\n`);

  if (values.ci && RISK_ORDER[analysis.summary.max_risk as Risk] >= RISK_ORDER.high) process.exit(1);
};

if (require.main === module) main();
