/* eslint-disable */
/**
 * Behavioral Signature Builder
 * =============================
 * Emits one hashed behavioral signature per HTTP route so CI can tell whether a change altered
 * what a route *does* rather than how it *looks*.
 *
 * Everything in the hash is derived from a single file's text: the route object
 * (`method`, `url`, `config.rateLimit`, lifecycle hooks, `verifyAuth([...])`), its request and
 * response schemas, the `server.services.<x>.<y>({...})` calls in its handler together with
 * the argument keys they are passed, and its import declarations resolved to module keys. That
 * property is what lets any git revision be signed without a checkout, which is what
 * `pr-behavior-diff.ts` relies on.
 *
 * Schemas are recorded two ways: the top-level field names (so a diff can say which field was
 * added) and a digest of the normalized schema text with `.describe(...)` and comments stripped
 * (so rewording a description is invisible but `.min(1)` -> `.min(8)` is not).
 *
 * SCOPE, stated plainly: a signature covers a route file's own surface. A change *inside* a
 * service - say `secretServiceFactory` gaining a DB write - does not alter any route file's
 * text and so does not move a hash. This is narrower than "behavioral signature" suggests.
 *
 * The Graphify graph (graphify-out/graph.json) is optional enrichment only. Its Leiden
 * community ids are reassigned and its community names are LLM-generated on every run, so
 * nothing graph-derived may enter the hash without churning it for free.
 *
 * Usage:
 *     npm run behavior:discover     # write .behavior-config.json
 *     npm run behavior:build        # write .behavior-manifest.json
 *     npm run behavior:diff -- --ci # committed manifest vs working tree
 *
 * See ./pr-behavior-diff.ts for diffing a pull request or any two git revisions.
 */

import { execFileSync } from "node:child_process";
import { createHash } from "node:crypto";
import { existsSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { parseArgs } from "node:util";

import ts from "typescript";

export const BACKEND_ROOT = path.resolve(__dirname, "..", "..");
export const REPO_ROOT = path.resolve(BACKEND_ROOT, "..");
export const BACKEND_PREFIX = `${path.basename(BACKEND_ROOT)}/`;

// graph.json lives at <repo>/graphify-out, but every source_file inside it is relative to
// <repo>/backend (graphify-out/.graphify_root points at backend).
export const DEFAULT_GRAPH = path.join(REPO_ROOT, "graphify-out", "graph.json");
export const DEFAULT_GRAPHIFY_MANIFEST = path.join(REPO_ROOT, "graphify-out", "manifest.json");
export const DEFAULT_CONFIG = path.join(BACKEND_ROOT, ".behavior-config.json");
export const DEFAULT_MANIFEST = path.join(BACKEND_ROOT, ".behavior-manifest.json");
const SOURCE_ROOT = path.join(BACKEND_ROOT, "src");

const DYNAMIC_URL = "<dynamic>";

export function fail(message: string): never {
  console.error(`\nerror: ${message}\n`);
  process.exit(2);
}

// ---------------------------------------------------------------------------
// Config
// ---------------------------------------------------------------------------

export interface BehaviorConfig {
  excluded_path_globs: string[];
  noise_bindings: string[];
  hook_keys: string[];
  graph_relations_behavioral: string[];
  graph_relations_ignored: string[];
  min_inferred_confidence: number;
}

const DEFAULT_CONFIG_VALUE: BehaviorConfig = {
  excluded_path_globs: [
    "src/db/**",
    "src/server/routes/bdd/**",
    "e2e-test/**",
    "bdd/**",
    "scripts/**",
    "*.test.ts",
    "package.json",
    "tsconfig*.json",
    "babel.config.json",
    ".eslintrc.js"
  ],
  noise_bindings: ["logger", "console", "sanitizeUrlForLog"],
  hook_keys: ["onRequest", "preParsing", "preValidation", "preHandler", "preSerialization", "onSend", "onResponse", "onError"],
  graph_relations_behavioral: ["imports", "imports_from", "calls", "re_exports", "references", "indirect_call", "method", "inherits", "extends", "implements", "defines", "dynamic_import", "shares_data_with"],
  graph_relations_ignored: ["contains", "rationale_for", "cites", "conceptually_related_to", "semantically_similar_to"],
  min_inferred_confidence: 0.9
};

const CONFIG_NOTES = [
  "Generated by `npm run behavior:discover`. Review, then commit alongside the manifest.",
  "",
  "The hash is computed entirely from a route file's own text, so any git revision can be",
  "signed without a checkout. Nothing graph-derived is hashed: Leiden community ids are",
  "reassigned and community names are LLM-generated on every graphify run, so hashing them",
  "would churn for free.",
  "",
  "excluded_path_globs: applied to a route file's path AND to each import's resolved path.",
  "  src/db/** is excluded because migrations are append-only and src/db/schemas is generated;",
  "  the tradeoff is that a real column change does not show up as a behavioral diff.",
  "noise_bindings: import bindings dropped from the hash, so adding a logger call does not",
  "  fail the gate even when it introduces the import.",
  "hook_keys: Fastify lifecycle hooks captured per route, in SOURCE ORDER, so reordering",
  "  middleware is a change. Every other array in the signature is deduped and sorted.",
  "graph_relations_*: used only by `discover` to report the graph vocabulary, and for the",
  "  optional unhashed enrichment block. They do not affect any hash."
];

export const loadConfig = (configPath: string): BehaviorConfig => {
  if (!existsSync(configPath)) {
    fail(
      `No behavior config at '${path.relative(BACKEND_ROOT, configPath)}'.\n` +
        `Run \`npm run behavior:discover\` first, review the generated file, then commit it.`
    );
  }
  const parsed = JSON.parse(readFileSync(configPath, "utf-8")) as Partial<BehaviorConfig>;
  return { ...DEFAULT_CONFIG_VALUE, ...parsed };
};

// ---------------------------------------------------------------------------
// Paths and module keys
// ---------------------------------------------------------------------------

const matchesGlob = (candidate: string, pattern: string): boolean => {
  if (pattern.endsWith("/**")) return candidate.startsWith(pattern.slice(0, -2));
  if (pattern.startsWith("*")) return candidate.endsWith(pattern.slice(1));
  if (pattern.endsWith("*")) return candidate.startsWith(pattern.slice(0, -1));
  return candidate === pattern || path.posix.basename(candidate) === pattern;
};

export const isExcludedPath = (sourceFile: string, config: BehaviorConfig): boolean =>
  config.excluded_path_globs.some((pattern) => matchesGlob(sourceFile, pattern));

// Path-derived and therefore stable across graphify runs, unlike Leiden community ids.
// Depth 3 under ee/ and server/ (which nest a category under the area), depth 2 elsewhere.
const moduleKeyOfPath = (p: string): string => {
  const stripped = p.replace(/^src\//, "");
  if (!stripped || stripped === ".") return "root";
  const segments = stripped.split("/").filter(Boolean);
  const depth = segments[0] === "ee" || segments[0] === "server" ? 3 : 2;
  return segments.slice(0, depth).join("/");
};

const moduleOfFile = (sourceFile: string): string => moduleKeyOfPath(path.posix.dirname(sourceFile));

interface ResolvedSpecifier {
  moduleKey: string;
  // Backend-relative path when the specifier points inside the backend, else null.
  sourcePath: string | null;
}

// No filesystem probing: the specifier path is used as-is, so a barrel ("@app/lib/errors") and
// a file ("@app/server/config/rateLimiter") both yield a stable key. Both sides of a diff run
// this same function, so comparability holds even where the key is more granular than the
// directory a symbol really lives in.
const resolveSpecifier = (specifier: string, fromFile: string): ResolvedSpecifier => {
  if (specifier.startsWith("node:")) {
    return { moduleKey: `node:${specifier.slice(5).split("/")[0]}`, sourcePath: null };
  }
  if (specifier.startsWith("@app/")) {
    const sourcePath = `src/${specifier.slice("@app/".length)}`;
    return { moduleKey: moduleKeyOfPath(sourcePath), sourcePath };
  }
  if (specifier.startsWith("@bdd_routes/")) {
    const sourcePath = `src/server/routes/bdd/${specifier.slice("@bdd_routes/".length)}`;
    return { moduleKey: moduleKeyOfPath(sourcePath), sourcePath };
  }
  if (specifier.startsWith(".")) {
    const joined = path.posix.normalize(path.posix.join(path.posix.dirname(fromFile), specifier));
    return { moduleKey: moduleKeyOfPath(joined), sourcePath: joined };
  }
  const segments = specifier.split("/");
  const name = specifier.startsWith("@") ? segments.slice(0, 2).join("/") : segments[0];
  return { moduleKey: `pkg:${name}`, sourcePath: null };
};

// ---------------------------------------------------------------------------
// Route extraction (TypeScript AST)
// ---------------------------------------------------------------------------

export interface CrossModuleDep {
  node: string;
  to: string;
  specifier: string;
}

interface FileImports {
  bindings: Set<string>;
  fileImports: string[];
  crossModuleDeps: CrossModuleDep[];
}

const readImports = (source: ts.SourceFile, relPath: string, config: BehaviorConfig): FileImports => {
  const ownModule = moduleOfFile(relPath);
  const noise = new Set(config.noise_bindings);

  const bindings = new Set<string>();
  const fileImports = new Set<string>();
  const crossByKey = new Map<string, CrossModuleDep>();

  for (const statement of source.statements) {
    if (!ts.isImportDeclaration(statement)) continue;
    if (!ts.isStringLiteral(statement.moduleSpecifier)) continue;
    const specifier = statement.moduleSpecifier.text;

    const names: string[] = [];
    const clause = statement.importClause;
    if (clause) {
      if (clause.name) names.push(clause.name.text);
      if (clause.namedBindings) {
        if (ts.isNamespaceImport(clause.namedBindings)) names.push(clause.namedBindings.name.text);
        else for (const element of clause.namedBindings.elements) names.push(element.name.text);
      }
    }
    for (const name of names) bindings.add(name);

    const { moduleKey, sourcePath } = resolveSpecifier(specifier, relPath);
    if (sourcePath && isExcludedPath(sourcePath, config)) continue;

    for (const name of names) {
      if (noise.has(name)) continue;
      if (moduleKey === ownModule) {
        fileImports.add(name);
      } else {
        const key = `${moduleKey}:${name}`;
        if (!crossByKey.has(key)) crossByKey.set(key, { node: name, to: moduleKey, specifier });
      }
    }
  }

  return {
    bindings,
    fileImports: [...fileImports].sort(),
    crossModuleDeps: [...crossByKey.values()].sort((a, b) => `${a.to}:${a.node}`.localeCompare(`${b.to}:${b.node}`))
  };
};

const literalText = (node: ts.Node): string | null => {
  if (ts.isStringLiteral(node) || ts.isNoSubstitutionTemplateLiteral(node)) return node.text;
  return null;
};

const propertyNamed = (obj: ts.ObjectLiteralExpression, name: string): ts.Expression | null => {
  for (const prop of obj.properties) {
    if (ts.isPropertyAssignment(prop) && prop.name && ts.isIdentifier(prop.name) && prop.name.text === name) {
      return prop.initializer;
    }
    if (ts.isShorthandPropertyAssignment(prop) && prop.name.text === name) return prop.name;
  }
  return null;
};

// Doc strings and formatting must not move a hash, but validator changes must. Comments and
// `.describe("...")` are stripped, then whitespace is collapsed, so reindenting or rewording a
// description is invisible while `.min(1)` -> `.min(8)` is not.
const stripDescribeCalls = (text: string): string => {
  let out = "";
  let index = 0;
  while (index < text.length) {
    const at = text.indexOf(".describe(", index);
    if (at === -1) {
      out += text.slice(index);
      break;
    }
    out += text.slice(index, at);
    let depth = 0;
    let cursor = at + ".describe".length;
    let quote: string | null = null;
    for (; cursor < text.length; cursor += 1) {
      const ch = text[cursor];
      if (quote) {
        if (ch === "\\") cursor += 1;
        else if (ch === quote) quote = null;
        continue;
      }
      if (ch === '"' || ch === "'" || ch === "`") quote = ch;
      else if (ch === "(") depth += 1;
      else if (ch === ")") {
        depth -= 1;
        if (depth === 0) {
          cursor += 1;
          break;
        }
      }
    }
    index = cursor;
  }
  return out;
};

const normalizeSchemaText = (text: string): string =>
  stripDescribeCalls(text)
    .replace(/\/\*[\s\S]*?\*\//g, "")
    .replace(/\/\/[^\n]*/g, "")
    .replace(/\s+/g, " ")
    .trim();

const schemaDigest = (node: ts.Node | null, source: ts.SourceFile): string =>
  node ? createHash("sha256").update(normalizeSchemaText(node.getText(source))).digest("hex").slice(0, 8) : "";

// Top-level keys of the first object literal under a schema section, so a diff can name the
// field that was added rather than only showing a digest change.
const schemaFieldNames = (node: ts.Node | null): string[] => {
  if (!node) return [];
  let found: ts.ObjectLiteralExpression | null = null;
  const visit = (current: ts.Node): void => {
    if (found) return;
    if (ts.isObjectLiteralExpression(current)) {
      found = current;
      return;
    }
    ts.forEachChild(current, visit);
  };
  visit(node);
  if (!found) return [];
  const names = (found as ts.ObjectLiteralExpression).properties
    .map((prop) => (prop.name ? prop.name.getText() : ts.isSpreadAssignment(prop) ? "..." : ""))
    .filter(Boolean);
  return [...new Set(names)].sort();
};

const calleeName = (call: ts.CallExpression): string | null => {
  const target = call.expression;
  if (ts.isIdentifier(target)) return target.text;
  if (ts.isPropertyAccessExpression(target)) return target.name.text;
  return null;
};

// `server.services.<service>.<method>` and `req.server.services.<service>.<method>`
const serviceCallOf = (node: ts.Node): string | null => {
  if (!ts.isPropertyAccessExpression(node)) return null;
  const method = node.name.text;
  const mid = node.expression;
  if (!ts.isPropertyAccessExpression(mid)) return null;
  const service = mid.name.text;
  const base = mid.expression;
  if (ts.isPropertyAccessExpression(base) && base.name.text === "services") return `${service}.${method}`;
  if (ts.isIdentifier(base) && base.text === "services") return `${service}.${method}`;
  return null;
};

const rootIdentifier = (node: ts.Expression): string | null => {
  let cursor: ts.Expression = node;
  while (ts.isPropertyAccessExpression(cursor)) cursor = cursor.expression;
  return ts.isIdentifier(cursor) ? cursor.text : null;
};

const enclosingRegisterFn = (node: ts.Node): string => {
  let cursor: ts.Node | undefined = node;
  while (cursor) {
    if (ts.isVariableDeclaration(cursor) && ts.isIdentifier(cursor.name)) return cursor.name.text;
    if (ts.isFunctionDeclaration(cursor) && cursor.name) return cursor.name.text;
    cursor = cursor.parent;
  }
  return "";
};

interface RouteSite {
  line: number;
  methods: string[];
  url: string | null;
  rateLimit: string;
  authModes: string[];
  hooks: string[];
  serviceCalls: string[];
  serviceCallArgs: string[];
  localCalls: string[];
  bodyFields: string[];
  paramsFields: string[];
  queryFields: string[];
  responseCodes: string[];
  bodySchema: string;
  paramsSchema: string;
  querySchema: string;
  responseSchema: string;
  registerFn: string;
  operationId: string;
  hidden: boolean;
}

const readRouteObject = (
  obj: ts.ObjectLiteralExpression,
  call: ts.CallExpression,
  source: ts.SourceFile,
  relPath: string,
  imports: FileImports,
  config: BehaviorConfig,
  warn: (message: string) => void
): RouteSite | null => {
  const line = source.getLineAndCharacterOfPosition(call.getStart()).line + 1;

  // A spread means this is a re-dispatch wrapper (src/server/lib/with-route-prefix.ts), not a
  // route definition.
  if (obj.properties.some((prop) => ts.isSpreadAssignment(prop))) {
    warn(`skipped re-dispatch wrapper at ${relPath}:${line} (route object uses a spread)`);
    return null;
  }

  const methodNode = propertyNamed(obj, "method");
  const urlNode = propertyNamed(obj, "url");
  if (!methodNode || !urlNode) {
    warn(`skipped route at ${relPath}:${line} (no method/url property)`);
    return null;
  }

  let methods: string[] = [];
  const single = literalText(methodNode);
  if (single) methods = [single.toUpperCase()];
  else if (ts.isArrayLiteralExpression(methodNode)) {
    methods = methodNode.elements
      .map((element) => literalText(element))
      .filter((value): value is string => !!value)
      .map((value) => value.toUpperCase());
  }
  if (!methods.length) {
    warn(`skipped route at ${relPath}:${line} (method is not a literal or array of literals)`);
    return null;
  }

  const url = literalText(urlNode);
  if (!url) warn(`route at ${relPath}:${line} has a non-literal url; recorded as '${DYNAMIC_URL}'`);

  const configNode = propertyNamed(obj, "config");
  let rateLimit = "";
  if (configNode && ts.isObjectLiteralExpression(configNode)) {
    const limit = propertyNamed(configNode, "rateLimit");
    if (limit) rateLimit = limit.getText(source);
  }

  const schemaNode = propertyNamed(obj, "schema");
  let operationId = "";
  let hidden = false;
  let bodyNode: ts.Expression | null = null;
  let paramsNode: ts.Expression | null = null;
  let queryNode: ts.Expression | null = null;
  let responseNode: ts.Expression | null = null;
  if (schemaNode && ts.isObjectLiteralExpression(schemaNode)) {
    const op = propertyNamed(schemaNode, "operationId");
    if (op) operationId = literalText(op) ?? "";
    hidden = propertyNamed(schemaNode, "hide")?.kind === ts.SyntaxKind.TrueKeyword;
    bodyNode = propertyNamed(schemaNode, "body");
    paramsNode = propertyNamed(schemaNode, "params");
    queryNode = propertyNamed(schemaNode, "querystring");
    responseNode = propertyNamed(schemaNode, "response");
  }

  const hooks: string[] = [];
  const authModes = new Set<string>();
  for (const hookKey of config.hook_keys) {
    const hookNode = propertyNamed(obj, hookKey);
    if (!hookNode) continue;
    const walkHook = (node: ts.Node): void => {
      if (ts.isCallExpression(node)) {
        const name = calleeName(node);
        if (name) hooks.push(`${hookKey}:${name}`);
        if (name === "verifyAuth" && node.arguments.length && ts.isArrayLiteralExpression(node.arguments[0])) {
          for (const element of (node.arguments[0] as ts.ArrayLiteralExpression).elements) {
            authModes.add(ts.isPropertyAccessExpression(element) ? element.name.text : element.getText(source));
          }
        }
      } else if (ts.isIdentifier(node) && node.parent === hookNode) {
        hooks.push(`${hookKey}:${node.text}`);
      }
      ts.forEachChild(node, walkHook);
    };
    walkHook(hookNode);
  }

  const serviceCalls = new Set<string>();
  const serviceCallArgs = new Set<string>();
  const localCalls = new Set<string>();
  const handlerNode = propertyNamed(obj, "handler");
  if (handlerNode) {
    const walkHandler = (node: ts.Node): void => {
      const service = serviceCallOf(node);
      if (service) serviceCalls.add(service);
      if (ts.isCallExpression(node)) {
        // The argument keys matter: handing a service `actorId`/`actorOrgId` it did not get
        // before is an authorization change, and the method name alone would not show it.
        const called = serviceCallOf(node.expression);
        if (called) {
          const first = node.arguments[0];
          const keys =
            first && ts.isObjectLiteralExpression(first)
              ? [
                  ...new Set(
                    first.properties
                      .map((prop) => (prop.name ? prop.name.getText(source) : ts.isSpreadAssignment(prop) ? "..." : ""))
                      .filter(Boolean)
                  )
                ].sort()
              : [];
          serviceCallArgs.add(`${called}:${keys.join(",")}`);
        }

        const root = rootIdentifier(node.expression);
        if (root && imports.bindings.has(root)) {
          localCalls.add(
            ts.isPropertyAccessExpression(node.expression) ? `${root}.${node.expression.name.text}` : root
          );
        }
      }
      ts.forEachChild(node, walkHandler);
    };
    walkHandler(handlerNode);
  }

  return {
    line,
    methods,
    url,
    rateLimit,
    authModes: [...authModes].sort(),
    hooks,
    serviceCalls: [...serviceCalls].sort(),
    serviceCallArgs: [...serviceCallArgs].sort(),
    localCalls: [...localCalls].sort(),
    bodyFields: schemaFieldNames(bodyNode),
    paramsFields: schemaFieldNames(paramsNode),
    queryFields: schemaFieldNames(queryNode),
    responseCodes: schemaFieldNames(responseNode),
    bodySchema: schemaDigest(bodyNode, source),
    paramsSchema: schemaDigest(paramsNode, source),
    querySchema: schemaDigest(queryNode, source),
    responseSchema: schemaDigest(responseNode, source),
    registerFn: enclosingRegisterFn(call),
    operationId,
    hidden
  };
};

// ---------------------------------------------------------------------------
// Signature
// ---------------------------------------------------------------------------

export interface GraphMeta {
  community: number | null;
  community_name: string;
  ast_hash: string;
  resolved: boolean;
}

export interface BehavioralSignature {
  method: string;
  url: string;
  feature: string;
  file: string;
  location: string;
  register_fn: string;
  operation_id: string;
  hidden: boolean;
  rate_limit: string;
  auth_modes: string[];
  hooks: string[];
  service_calls: string[];
  service_call_args: string[];
  local_calls: string[];
  body_fields: string[];
  params_fields: string[];
  query_fields: string[];
  response_codes: string[];
  body_schema: string;
  params_schema: string;
  query_schema: string;
  response_schema: string;
  file_imports: string[];
  cross_module_deps: CrossModuleDep[];
  graph?: GraphMeta;
  hash: string;
}

// Hashed as an array of pairs so key order is fixed by construction, with no post-hoc string
// surgery. `hooks` keeps source order so reordering middleware registers as a change;
// everything else is deduped and sorted upstream. location, register_fn, operation_id and the
// graph block are metadata and deliberately absent.
const computeHash = (signature: BehavioralSignature): string => {
  const payload: [string, unknown][] = [
    ["method", signature.method],
    ["url", signature.url],
    ["feature", signature.feature],
    ["rate_limit", signature.rate_limit],
    ["auth_modes", signature.auth_modes],
    ["hooks", signature.hooks],
    ["service_calls", signature.service_calls],
    ["service_call_args", signature.service_call_args],
    ["local_calls", signature.local_calls],
    ["body_fields", signature.body_fields],
    ["params_fields", signature.params_fields],
    ["query_fields", signature.query_fields],
    ["response_codes", signature.response_codes],
    ["body_schema", signature.body_schema],
    ["params_schema", signature.params_schema],
    ["query_schema", signature.query_schema],
    ["response_schema", signature.response_schema],
    ["file_imports", signature.file_imports],
    ["cross_module_deps", signature.cross_module_deps.map((dep) => `${dep.to}:${dep.node}`).sort()]
  ];
  return createHash("sha256").update(JSON.stringify(payload)).digest("hex").slice(0, 12);
};

export const signaturesForFile = (
  relPath: string,
  text: string,
  config: BehaviorConfig,
  warn: (message: string) => void
): BehavioralSignature[] => {
  if (!text.includes(".route({")) return [];

  const source = ts.createSourceFile(relPath, text, ts.ScriptTarget.Latest, true, ts.ScriptKind.TS);
  const imports = readImports(source, relPath, config);
  const feature = moduleOfFile(relPath);
  const signatures: BehavioralSignature[] = [];

  const visit = (node: ts.Node): void => {
    if (
      ts.isCallExpression(node) &&
      ts.isPropertyAccessExpression(node.expression) &&
      node.expression.name.text === "route" &&
      node.arguments.length === 1 &&
      ts.isObjectLiteralExpression(node.arguments[0])
    ) {
      const site = readRouteObject(
        node.arguments[0] as ts.ObjectLiteralExpression,
        node,
        source,
        relPath,
        imports,
        config,
        warn
      );
      if (site) {
        for (const method of site.methods) {
          const signature: BehavioralSignature = {
            method,
            url: site.url ?? DYNAMIC_URL,
            feature,
            file: relPath,
            location: `L${site.line}`,
            register_fn: site.registerFn,
            operation_id: site.operationId,
            hidden: site.hidden,
            rate_limit: site.rateLimit,
            auth_modes: site.authModes,
            hooks: site.hooks,
            service_calls: site.serviceCalls,
            service_call_args: site.serviceCallArgs,
            local_calls: site.localCalls,
            body_fields: site.bodyFields,
            params_fields: site.paramsFields,
            query_fields: site.queryFields,
            response_codes: site.responseCodes,
            body_schema: site.bodySchema,
            params_schema: site.paramsSchema,
            query_schema: site.querySchema,
            response_schema: site.responseSchema,
            file_imports: imports.fileImports,
            cross_module_deps: imports.crossModuleDeps,
            hash: ""
          };
          signature.hash = computeHash(signature);
          signatures.push(signature);
        }
      }
    }
    ts.forEachChild(node, visit);
  };
  visit(source);

  return signatures;
};

// ---------------------------------------------------------------------------
// Manifest
// ---------------------------------------------------------------------------

export interface Manifest {
  _meta: {
    revision: string;
    scope: string;
    route_count: number;
    file_count: number;
    graph_commit?: string;
  };
  routes: Record<string, BehavioralSignature>;
}

export const assemble = (
  entries: BehavioralSignature[],
  meta: Manifest["_meta"],
  warn: (message: string) => void
): Manifest => {
  const routes: Record<string, BehavioralSignature> = {};
  for (const signature of entries) {
    // Never overwrite: a collision would silently drop a route from the gate.
    const base = `${signature.file}::${signature.method} ${signature.url}`;
    let key = base;
    let ordinal = 2;
    while (key in routes) {
      key = `${base}#${ordinal}`;
      ordinal += 1;
    }
    if (key !== base) warn(`duplicate route key '${base}', recorded as '${key}'`);
    routes[key] = signature;
  }

  const ordered: Record<string, BehavioralSignature> = {};
  for (const key of Object.keys(routes).sort()) ordered[key] = routes[key];

  return {
    _meta: { ...meta, route_count: Object.keys(ordered).length, file_count: new Set(entries.map((s) => s.file)).size },
    routes: ordered
  };
};

const collectSourceFiles = (dir: string, acc: string[] = []): string[] => {
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      if (entry.name === "node_modules") continue;
      collectSourceFiles(full, acc);
    } else if (entry.name.endsWith(".ts") || entry.name.endsWith(".tsx")) {
      acc.push(full);
    }
  }
  return acc;
};

export const buildFromWorkingTree = (
  config: BehaviorConfig,
  warn: (message: string) => void
): BehavioralSignature[] => {
  const entries: BehavioralSignature[] = [];
  for (const absPath of collectSourceFiles(SOURCE_ROOT)) {
    const relPath = path.relative(BACKEND_ROOT, absPath).split(path.sep).join("/");
    if (isExcludedPath(relPath, config)) continue;
    entries.push(...signaturesForFile(relPath, readFileSync(absPath, "utf-8"), config, warn));
  }
  return entries;
};

// ---------------------------------------------------------------------------
// Optional graph enrichment (never hashed)
// ---------------------------------------------------------------------------

interface GraphNodeRaw {
  id: string;
  label?: string;
  source_file?: string;
  community?: number;
  community_name?: string;
  _callable?: boolean;
}

interface GraphLinkRaw {
  source: string | { id: string };
  target: string | { id: string };
  relation?: string;
  confidence?: string;
}

interface GraphSummary {
  commit: string;
  nodes: number;
  edges: number;
  fileNodes: number;
  communities: number;
  relations: Record<string, number>;
  confidence: Record<string, number>;
  byFile: Map<string, { community: number | null; communityName: string }>;
  importDegree: { label: string; sourceFile: string; count: number }[];
}

const idOf = (value: string | { id: string }): string => (typeof value === "string" ? value : value.id);

const loadGraph = (graphPath: string): GraphSummary | null => {
  if (!existsSync(graphPath)) return null;

  const data = JSON.parse(readFileSync(graphPath, "utf-8")) as {
    nodes?: GraphNodeRaw[];
    links?: GraphLinkRaw[];
    edges?: GraphLinkRaw[];
    built_at_commit?: string;
  };

  const byId = new Map<string, GraphNodeRaw>();
  const byFile = new Map<string, { community: number | null; communityName: string }>();
  const communities = new Set<number | null>();

  for (const node of data.nodes ?? []) {
    byId.set(node.id, node);
    // community is an integer and 0 is a real community - never coerce it away.
    const community = typeof node.community === "number" ? node.community : null;
    communities.add(community);

    const sourceFile = node.source_file ?? "";
    const label = node.label ?? "";
    if (!sourceFile || node._callable) continue;
    const base = path.posix.basename(sourceFile);
    if (label === base || label.endsWith(`/${base}`)) {
      byFile.set(sourceFile, { community, communityName: node.community_name ?? "" });
    }
  }

  const links = data.links ?? data.edges ?? [];
  const relations: Record<string, number> = {};
  const confidence: Record<string, number> = {};
  const degree = new Map<string, number>();
  for (const link of links) {
    const relation = link.relation ?? "unknown";
    relations[relation] = (relations[relation] ?? 0) + 1;
    const conf = link.confidence ?? "EXTRACTED";
    confidence[conf] = (confidence[conf] ?? 0) + 1;
    if (relation === "imports" || relation === "imports_from") {
      const target = idOf(link.target);
      degree.set(target, (degree.get(target) ?? 0) + 1);
    }
  }

  const importDegree = [...degree.entries()]
    .sort((a, b) => b[1] - a[1])
    .slice(0, 25)
    .map(([id, count]) => ({
      label: byId.get(id)?.label ?? id,
      sourceFile: byId.get(id)?.source_file ?? "",
      count
    }));

  return {
    commit: data.built_at_commit ?? "",
    nodes: byId.size,
    edges: links.length,
    fileNodes: byFile.size,
    communities: communities.size,
    relations: Object.fromEntries(Object.entries(relations).sort((a, b) => b[1] - a[1])),
    confidence: Object.fromEntries(Object.entries(confidence).sort((a, b) => b[1] - a[1])),
    byFile,
    importDegree
  };
};

export const loadAstHashes = (): Map<string, string> => {
  const hashes = new Map<string, string>();
  if (!existsSync(DEFAULT_GRAPHIFY_MANIFEST)) return hashes;
  const raw = JSON.parse(readFileSync(DEFAULT_GRAPHIFY_MANIFEST, "utf-8")) as Record<string, { ast_hash?: string }>;
  for (const [file, entry] of Object.entries(raw)) if (entry?.ast_hash) hashes.set(file, entry.ast_hash);
  return hashes;
};

const enrich = (entries: BehavioralSignature[], graph: GraphSummary | null): void => {
  if (!graph) return;
  const astHashes = loadAstHashes();
  for (const signature of entries) {
    const node = graph.byFile.get(signature.file);
    signature.graph = {
      community: node?.community ?? null,
      community_name: node?.communityName ?? "",
      ast_hash: astHashes.get(signature.file) ?? "",
      resolved: !!node
    };
  }
};

// ---------------------------------------------------------------------------
// Diff
// ---------------------------------------------------------------------------

export interface ChangeDetail {
  field: string;
  added: string[];
  removed: string[];
}

// Provenance for ./project-analyzer.ts, which is a pure join over this report and never shells
// out to git. changed_files carries EVERY backend/src file in the diff, not just route files:
// the whole point of the analyzer is to reach the routes a service-only change touches, which by
// construction move no hash and so appear nowhere else in this report.
export interface DiffReportMeta {
  base: string;
  head: string;
  pr?: { slug: string; number: number };
  changed_files: string[];
  // Head-side changed line ranges per file. Consumed by ./method-index.ts to resolve a change to
  // the methods it lands in; absent on reports written before that existed.
  changed_hunks?: Record<string, { start: number; end: number }[]>;
  generated_at: string;
}

export interface DiffReport {
  scope: string;
  meta?: DiffReportMeta;
  added: { route: string; signature: BehavioralSignature }[];
  removed: { route: string; signature: BehavioralSignature }[];
  changed: { route: string; before: BehavioralSignature; after: BehavioralSignature; details: ChangeDetail[] }[];
  unchanged: number;
}

const SCALAR_FIELDS: (keyof BehavioralSignature)[] = [
  "method",
  "url",
  "feature",
  "rate_limit",
  "body_schema",
  "params_schema",
  "query_schema",
  "response_schema"
];
const LIST_FIELDS: (keyof BehavioralSignature)[] = [
  "auth_modes",
  "hooks",
  "service_calls",
  "service_call_args",
  "local_calls",
  "body_fields",
  "params_fields",
  "query_fields",
  "response_codes",
  "file_imports"
];

const explainChange = (before: BehavioralSignature, after: BehavioralSignature): ChangeDetail[] => {
  const changes: ChangeDetail[] = [];

  for (const field of SCALAR_FIELDS) {
    const from = String(before[field] ?? "");
    const to = String(after[field] ?? "");
    if (from !== to) changes.push({ field, added: to ? [to] : [], removed: from ? [from] : [] });
  }

  for (const field of LIST_FIELDS) {
    const fromSet = new Set((before[field] as string[] | undefined) ?? []);
    const toSet = new Set((after[field] as string[] | undefined) ?? []);
    const added = [...toSet].filter((value) => !fromSet.has(value)).sort();
    const removed = [...fromSet].filter((value) => !toSet.has(value)).sort();
    if (added.length || removed.length) changes.push({ field, added, removed });
  }

  const key = (dep: CrossModuleDep) => `${dep.to}:${dep.node}`;
  const fromCross = new Set((before.cross_module_deps ?? []).map(key));
  const toCross = new Set((after.cross_module_deps ?? []).map(key));
  const addedCross = [...toCross].filter((value) => !fromCross.has(value)).sort();
  const removedCross = [...fromCross].filter((value) => !toCross.has(value)).sort();
  if (addedCross.length || removedCross.length) {
    changes.push({ field: "cross_module_deps", added: addedCross, removed: removedCross });
  }

  // hooks are order-sensitive by design, so a pure reorder shows no set difference.
  if (!changes.length && JSON.stringify(before.hooks) !== JSON.stringify(after.hooks)) {
    changes.push({ field: "hooks (reordered)", added: after.hooks, removed: before.hooks });
  }

  return changes;
};

export const diffManifests = (baseline: Manifest, current: Manifest, scope: string): DiffReport => {
  const report: DiffReport = { scope, added: [], removed: [], changed: [], unchanged: 0 };
  const before = baseline.routes ?? {};
  const after = current.routes ?? {};

  for (const [route, signature] of Object.entries(after)) {
    const previous = before[route];
    if (!previous) report.added.push({ route, signature });
    else if (previous.hash !== signature.hash) {
      report.changed.push({ route, before: previous, after: signature, details: explainChange(previous, signature) });
    } else report.unchanged += 1;
  }

  for (const [route, signature] of Object.entries(before)) {
    if (!(route in after)) report.removed.push({ route, signature });
  }

  report.added.sort((a, b) => a.route.localeCompare(b.route));
  report.removed.sort((a, b) => a.route.localeCompare(b.route));
  report.changed.sort((a, b) => a.route.localeCompare(b.route));
  return report;
};

export const formatReport = (report: DiffReport): string => {
  const lines: string[] = ["", "  Behavior Change Report", ""];

  for (const item of report.changed) {
    lines.push(`  CHANGED: ${item.route}  (feature: ${item.after.feature})`);
    lines.push(`     hash: ${item.before.hash} -> ${item.after.hash}`);
    for (const change of item.details) {
      for (const value of change.added) lines.push(`     + ${change.field}: ${value}`);
      for (const value of change.removed) lines.push(`     - ${change.field}: ${value}`);
    }
    lines.push("");
  }

  for (const item of report.added) {
    lines.push(`  NEW: ${item.route}  (feature: ${item.signature.feature})`);
    if (item.signature.service_calls.length) {
      lines.push(`     services: ${item.signature.service_calls.slice(0, 5).join(", ")}`);
    }
    if (item.signature.auth_modes.length) lines.push(`     auth: ${item.signature.auth_modes.join(", ")}`);
    const modules = [...new Set(item.signature.cross_module_deps.map((dep) => dep.to))].sort();
    if (modules.length) lines.push(`     touches: ${modules.slice(0, 6).join(", ")}`);
    lines.push("");
  }

  for (const item of report.removed) lines.push(`  REMOVED: ${item.route}`);
  if (report.removed.length) lines.push("");

  const total = report.unchanged + report.changed.length + report.added.length + report.removed.length;
  lines.push(
    `  Summary: ${report.changed.length} changed, ${report.added.length} new, ` +
      `${report.removed.length} removed, ${report.unchanged} unchanged out of ${total} routes`
  );
  lines.push(`  Scope: ${report.scope}`);

  return lines.join("\n");
};

// Tracked edits plus untracked additions, so `behavior:diff` against the working tree can hand
// ./project-analyzer.ts the same changed_files list a pull request diff would.
export const workingTreeChangedFiles = (): string[] => {
  const run = (args: string[]): string[] => {
    try {
      return execFileSync("git", args, { cwd: REPO_ROOT, encoding: "utf-8", maxBuffer: 64 * 1024 * 1024 })
        .split("\n")
        .map((line) => line.trim())
        .filter(Boolean);
    } catch {
      return [];
    }
  };

  const scope = `${BACKEND_PREFIX}src`;
  const files = [
    ...run(["diff", "--name-only", "HEAD", "--", scope]),
    ...run(["ls-files", "--others", "--exclude-standard", "--", scope])
  ];
  return [...new Set(files.map((file) => file.slice(BACKEND_PREFIX.length)))].sort();
};

export const collectWarnings = () => {
  const warnings: string[] = [];
  return { warn: (message: string) => warnings.push(message), flush: () => warnings };
};

export const printWarnings = (warnings: string[]): void => {
  const seen = new Set<string>();
  for (const message of warnings) {
    if (seen.has(message)) continue;
    seen.add(message);
    console.warn(`  warn: ${message}`);
  }
};

export const finishDiff = (report: DiffReport, reportPath: string | undefined, ci: boolean): void => {
  console.log(formatReport(report));
  if (reportPath) writeFileSync(path.resolve(reportPath), `${JSON.stringify(report, null, 2)}\n`);
  if (ci && (report.changed.length || report.added.length || report.removed.length)) process.exit(1);
};

// ---------------------------------------------------------------------------
// Commands
// ---------------------------------------------------------------------------

const commandDiscover = (graphPath: string, configPath: string): void => {
  const graph = loadGraph(graphPath);
  const output: Record<string, unknown> = { _notes: CONFIG_NOTES };

  if (graph) {
    const known = new Set([
      ...DEFAULT_CONFIG_VALUE.graph_relations_behavioral,
      ...DEFAULT_CONFIG_VALUE.graph_relations_ignored
    ]);
    const unclassified = Object.entries(graph.relations)
      .filter(([relation]) => !known.has(relation))
      .map(([relation, count]) => `${relation} (${count})`);

    output._graph = {
      path: path.relative(BACKEND_ROOT, graphPath),
      built_at_commit: graph.commit,
      nodes: graph.nodes,
      edges: graph.edges,
      file_nodes: graph.fileNodes,
      communities: graph.communities,
      relations: graph.relations,
      confidence: graph.confidence,
      unclassified_relations: unclassified
    };
    output._noise_candidates = graph.importDegree.map((entry) => `${entry.label} (${entry.count}) - ${entry.sourceFile}`);

    console.log(
      `Graph: ${graph.nodes} nodes, ${graph.edges} edges, ${graph.fileNodes} file nodes, ${graph.communities} communities`
    );
    if (unclassified.length) console.log(`  Unclassified relations: ${unclassified.join(", ")}`);
  } else {
    console.log(`No graph at ${graphPath} - writing config without graph enrichment (hashes never use it).`);
  }

  const { warn, flush } = collectWarnings();
  const entries = buildFromWorkingTree(DEFAULT_CONFIG_VALUE, warn);
  printWarnings(flush());

  output._routes = {
    total: entries.length,
    files: new Set(entries.map((s) => s.file)).size,
    features: [...new Set(entries.map((s) => s.feature))].sort()
  };
  Object.assign(output, DEFAULT_CONFIG_VALUE);

  writeFileSync(configPath, `${JSON.stringify(output, null, 2)}\n`);
  console.log(`Routes: ${entries.length} across ${new Set(entries.map((s) => s.file)).size} files`);
  console.log(`\nConfig written to ${path.relative(BACKEND_ROOT, configPath)} - review and commit it.`);
};

const commandBuild = (graphPath: string, configPath: string, outputPath: string): void => {
  const config = loadConfig(configPath);
  const { warn, flush } = collectWarnings();
  const entries = buildFromWorkingTree(config, warn);
  const graph = loadGraph(graphPath);
  enrich(entries, graph);

  let revision = "working-tree";
  try {
    revision = `working-tree@${execFileSync("git", ["rev-parse", "--short", "HEAD"], {
      cwd: REPO_ROOT,
      encoding: "utf-8"
    }).trim()}`;
  } catch {
    /* not a git checkout */
  }

  const manifest = assemble(
    entries,
    { revision, scope: "backend/src", route_count: 0, file_count: 0, graph_commit: graph?.commit },
    warn
  );
  printWarnings(flush());

  writeFileSync(outputPath, `${JSON.stringify(manifest, null, 2)}\n`);
  console.log(
    `\nManifest written to ${path.relative(BACKEND_ROOT, outputPath)}\n` +
      `  Routes:   ${manifest._meta.route_count}\n` +
      `  Files:    ${manifest._meta.file_count}\n` +
      `  Features: ${new Set(Object.values(manifest.routes).map((s) => s.feature)).size}\n` +
      `  Graph:    ${graph ? `${graph.commit.slice(0, 12)} (metadata only)` : "absent (not required)"}`
  );
};

const commandDiff = (
  configPath: string,
  baselinePath: string,
  reportPath: string | undefined,
  ci: boolean
): void => {
  if (!existsSync(baselinePath)) {
    fail(
      `No baseline manifest at '${path.relative(BACKEND_ROOT, baselinePath)}'.\n` +
        `Run \`npm run behavior:build\` on the base revision and commit the result first.`
    );
  }
  const config = loadConfig(configPath);
  const { warn, flush } = collectWarnings();
  const baseline = JSON.parse(readFileSync(baselinePath, "utf-8")) as Manifest;
  const current = assemble(
    buildFromWorkingTree(config, warn),
    { revision: "working-tree", scope: "backend/src", route_count: 0, file_count: 0 },
    warn
  );
  printWarnings(flush());

  const report = diffManifests(baseline, current, "backend/src (whole tree)");
  report.meta = {
    base: baseline._meta?.revision ?? "committed-manifest",
    head: "working-tree",
    changed_files: workingTreeChangedFiles(),
    generated_at: new Date().toISOString()
  };
  finishDiff(report, reportPath, ci);
};

const USAGE = `Usage: tsx ./scripts/graphs/signature-builder.ts <command> [options]

Commands:
  discover    Inspect the tree (and graph, if present) and write .behavior-config.json
  build       Write .behavior-manifest.json for the working tree
  diff        Compare the working tree against a committed manifest

Options:
  --graph PATH       graph.json for unhashed enrichment (default: ../graphify-out/graph.json)
  --config PATH      behavior config (default: backend/.behavior-config.json)
  --output PATH      manifest to write (build) (default: backend/.behavior-manifest.json)
  --baseline PATH    manifest to compare against (diff) (default: --output)
  --report PATH      also write the diff report as JSON
  --ci               exit 1 when behavior changed
  -h, --help         show this message

To diff a pull request or two git revisions, see ./pr-behavior-diff.ts
`;

const main = (): void => {
  const { values, positionals } = parseArgs({
    allowPositionals: true,
    options: {
      graph: { type: "string" },
      config: { type: "string" },
      output: { type: "string" },
      baseline: { type: "string" },
      report: { type: "string" },
      ci: { type: "boolean", default: false },
      help: { type: "boolean", short: "h", default: false }
    }
  });

  const command = positionals[0];
  if (values.help || !command) {
    console.log(USAGE);
    process.exit(values.help ? 0 : 2);
  }

  const graphPath = path.resolve(values.graph ?? DEFAULT_GRAPH);
  const configPath = path.resolve(values.config ?? DEFAULT_CONFIG);
  const outputPath = path.resolve(values.output ?? DEFAULT_MANIFEST);

  switch (command) {
    case "discover":
      commandDiscover(graphPath, configPath);
      return;
    case "build":
      commandBuild(graphPath, configPath, outputPath);
      return;
    case "diff":
      commandDiff(configPath, path.resolve(values.baseline ?? outputPath), values.report, values.ci ?? false);
      return;
    default:
      fail(`Unknown command '${command}'.\n${USAGE}`);
  }
};

if (require.main === module) main();
